infix using "C:\COUNTRIES\RW41\RWHR41FL.dct"

label variable hhid     "Case Identification"
label variable hv000    "Country code and phase"
label variable hv001    "Cluster number"
label variable hv002    "Household number"
label variable hv003    "Respondent's line number"
label variable hv004    "Ultimate area unit"
label variable hv005    "Sample weight"
label variable hv006    "Month of interview"
label variable hv007    "Year of interview"
label variable hv008    "Date of interview (CMC)"
label variable hv009    "Number of household members"
label variable hv010    "Number of eligible women in HH"
label variable hv011    "Number of eligible men in HH"
label variable hv012    "Number of de jure members"
label variable hv013    "Number of de facto members"
label variable hv014    "Number of children 5 and under"
label variable hv015    "Result of household interview"
label variable hv016    "Day of interview"
label variable hv017    "Number of visits"
label variable hv018    "Interviewer identification"
label variable hv019    "Keyer identification"
label variable hv020    "Ever-married sample"
label variable hv021    "Primary sampling unit"
label variable hv022    "Sample stratum number"
label variable hv023    "Sample domain"
label variable hv024    "Region"
label variable hv025    "Type of place of residence"
label variable hv026    "Place of residence"
label variable hv027    "Selection for male/husb. int."
label variable hv028    "Sample weight for male subsamp"
label variable hv030    "Field supervisor"
label variable hv031    "Field editor"
label variable hv032    "Office editor"
label variable hv033    "Ultimate area selection prob."
label variable hv035    "Number of eligible children for height & weight"
label variable hv040    "Cluster altitude in meters-NA"
label variable hv041    "Total adults measured"
label variable hv042    "Selection for hemoglo-NA  -NA"
label variable hv043    "Selection for women's stat-NA"
label variable hv044    "Selection for domestic vio-NA"
label variable hv201    "Source of drinking water"
label variable hv204    "Time to get to water source"
label variable hv205    "Type of toilet facility"
label variable hv206    "Has electricity"
label variable hv207    "Has radio"
label variable hv208    "Has television"
label variable hv209    "Has refrigerator"
label variable hv210    "Has bicycle"
label variable hv211    "Has motorcycle/scooter"
label variable hv212    "Has car/truck"
label variable hv213    "Main floor material"
label variable hv214    "Main wall material        -NA"
label variable hv215    "Main roof material        -NA"
label variable hv217    "Relationship structure"
label variable hv218    "Line number of head of househ."
label variable hv219    "Sex of head of household"
label variable hv220    "Age of head of household"
label variable hv221    "Has telephone"
label variable hv225    "Share toilet with other households"
label variable hv226    "Type of cooking fuel"
label variable hv227    "Have bednet for sleeping"
label variable hv228    "Children under 5 slept under bednet last night"
label variable hv230    "Place for hand washing"
label variable hv231    "Items present: Water, tap"
label variable hv232    "Items present: soap/other cleansing agent"
label variable hv233    "Items present: Basin"
label variable hv234    "Test salt for Iodine"
label variable shcommu  "Commune"
label variable shinter  "Interpreter"
label variable shlang   "Languuage of interview"
label variable shsecte  "Secteur"
label variable shtime   "Time to enter household questionnaire"
label variable hvidx_01 "Line number"
label variable hvidx_02 "Line number"
label variable hvidx_03 "Line number"
label variable hvidx_04 "Line number"
label variable hvidx_05 "Line number"
label variable hvidx_06 "Line number"
label variable hvidx_07 "Line number"
label variable hvidx_08 "Line number"
label variable hvidx_09 "Line number"
label variable hvidx_10 "Line number"
label variable hvidx_11 "Line number"
label variable hvidx_12 "Line number"
label variable hvidx_13 "Line number"
label variable hvidx_14 "Line number"
label variable hvidx_15 "Line number"
label variable hvidx_16 "Line number"
label variable hvidx_17 "Line number"
label variable hvidx_18 "Line number"
label variable hvidx_19 "Line number"
label variable hvidx_20 "Line number"
label variable hv101_01 "Relationship to head"
label variable hv101_02 "Relationship to head"
label variable hv101_03 "Relationship to head"
label variable hv101_04 "Relationship to head"
label variable hv101_05 "Relationship to head"
label variable hv101_06 "Relationship to head"
label variable hv101_07 "Relationship to head"
label variable hv101_08 "Relationship to head"
label variable hv101_09 "Relationship to head"
label variable hv101_10 "Relationship to head"
label variable hv101_11 "Relationship to head"
label variable hv101_12 "Relationship to head"
label variable hv101_13 "Relationship to head"
label variable hv101_14 "Relationship to head"
label variable hv101_15 "Relationship to head"
label variable hv101_16 "Relationship to head"
label variable hv101_17 "Relationship to head"
label variable hv101_18 "Relationship to head"
label variable hv101_19 "Relationship to head"
label variable hv101_20 "Relationship to head"
label variable hv102_01 "Usual resident"
label variable hv102_02 "Usual resident"
label variable hv102_03 "Usual resident"
label variable hv102_04 "Usual resident"
label variable hv102_05 "Usual resident"
label variable hv102_06 "Usual resident"
label variable hv102_07 "Usual resident"
label variable hv102_08 "Usual resident"
label variable hv102_09 "Usual resident"
label variable hv102_10 "Usual resident"
label variable hv102_11 "Usual resident"
label variable hv102_12 "Usual resident"
label variable hv102_13 "Usual resident"
label variable hv102_14 "Usual resident"
label variable hv102_15 "Usual resident"
label variable hv102_16 "Usual resident"
label variable hv102_17 "Usual resident"
label variable hv102_18 "Usual resident"
label variable hv102_19 "Usual resident"
label variable hv102_20 "Usual resident"
label variable hv103_01 "Slept last night"
label variable hv103_02 "Slept last night"
label variable hv103_03 "Slept last night"
label variable hv103_04 "Slept last night"
label variable hv103_05 "Slept last night"
label variable hv103_06 "Slept last night"
label variable hv103_07 "Slept last night"
label variable hv103_08 "Slept last night"
label variable hv103_09 "Slept last night"
label variable hv103_10 "Slept last night"
label variable hv103_11 "Slept last night"
label variable hv103_12 "Slept last night"
label variable hv103_13 "Slept last night"
label variable hv103_14 "Slept last night"
label variable hv103_15 "Slept last night"
label variable hv103_16 "Slept last night"
label variable hv103_17 "Slept last night"
label variable hv103_18 "Slept last night"
label variable hv103_19 "Slept last night"
label variable hv103_20 "Slept last night"
label variable hv104_01 "Sex of household member"
label variable hv104_02 "Sex of household member"
label variable hv104_03 "Sex of household member"
label variable hv104_04 "Sex of household member"
label variable hv104_05 "Sex of household member"
label variable hv104_06 "Sex of household member"
label variable hv104_07 "Sex of household member"
label variable hv104_08 "Sex of household member"
label variable hv104_09 "Sex of household member"
label variable hv104_10 "Sex of household member"
label variable hv104_11 "Sex of household member"
label variable hv104_12 "Sex of household member"
label variable hv104_13 "Sex of household member"
label variable hv104_14 "Sex of household member"
label variable hv104_15 "Sex of household member"
label variable hv104_16 "Sex of household member"
label variable hv104_17 "Sex of household member"
label variable hv104_18 "Sex of household member"
label variable hv104_19 "Sex of household member"
label variable hv104_20 "Sex of household member"
label variable hv105_01 "Age of household members"
label variable hv105_02 "Age of household members"
label variable hv105_03 "Age of household members"
label variable hv105_04 "Age of household members"
label variable hv105_05 "Age of household members"
label variable hv105_06 "Age of household members"
label variable hv105_07 "Age of household members"
label variable hv105_08 "Age of household members"
label variable hv105_09 "Age of household members"
label variable hv105_10 "Age of household members"
label variable hv105_11 "Age of household members"
label variable hv105_12 "Age of household members"
label variable hv105_13 "Age of household members"
label variable hv105_14 "Age of household members"
label variable hv105_15 "Age of household members"
label variable hv105_16 "Age of household members"
label variable hv105_17 "Age of household members"
label variable hv105_18 "Age of household members"
label variable hv105_19 "Age of household members"
label variable hv105_20 "Age of household members"
label variable hv106_01 "Highest educational level"
label variable hv106_02 "Highest educational level"
label variable hv106_03 "Highest educational level"
label variable hv106_04 "Highest educational level"
label variable hv106_05 "Highest educational level"
label variable hv106_06 "Highest educational level"
label variable hv106_07 "Highest educational level"
label variable hv106_08 "Highest educational level"
label variable hv106_09 "Highest educational level"
label variable hv106_10 "Highest educational level"
label variable hv106_11 "Highest educational level"
label variable hv106_12 "Highest educational level"
label variable hv106_13 "Highest educational level"
label variable hv106_14 "Highest educational level"
label variable hv106_15 "Highest educational level"
label variable hv106_16 "Highest educational level"
label variable hv106_17 "Highest educational level"
label variable hv106_18 "Highest educational level"
label variable hv106_19 "Highest educational level"
label variable hv106_20 "Highest educational level"
label variable hv107_01 "Highest year of education"
label variable hv107_02 "Highest year of education"
label variable hv107_03 "Highest year of education"
label variable hv107_04 "Highest year of education"
label variable hv107_05 "Highest year of education"
label variable hv107_06 "Highest year of education"
label variable hv107_07 "Highest year of education"
label variable hv107_08 "Highest year of education"
label variable hv107_09 "Highest year of education"
label variable hv107_10 "Highest year of education"
label variable hv107_11 "Highest year of education"
label variable hv107_12 "Highest year of education"
label variable hv107_13 "Highest year of education"
label variable hv107_14 "Highest year of education"
label variable hv107_15 "Highest year of education"
label variable hv107_16 "Highest year of education"
label variable hv107_17 "Highest year of education"
label variable hv107_18 "Highest year of education"
label variable hv107_19 "Highest year of education"
label variable hv107_20 "Highest year of education"
label variable hv108_01 "Education in single years"
label variable hv108_02 "Education in single years"
label variable hv108_03 "Education in single years"
label variable hv108_04 "Education in single years"
label variable hv108_05 "Education in single years"
label variable hv108_06 "Education in single years"
label variable hv108_07 "Education in single years"
label variable hv108_08 "Education in single years"
label variable hv108_09 "Education in single years"
label variable hv108_10 "Education in single years"
label variable hv108_11 "Education in single years"
label variable hv108_12 "Education in single years"
label variable hv108_13 "Education in single years"
label variable hv108_14 "Education in single years"
label variable hv108_15 "Education in single years"
label variable hv108_16 "Education in single years"
label variable hv108_17 "Education in single years"
label variable hv108_18 "Education in single years"
label variable hv108_19 "Education in single years"
label variable hv108_20 "Education in single years"
label variable hv109_01 "Educational attainment"
label variable hv109_02 "Educational attainment"
label variable hv109_03 "Educational attainment"
label variable hv109_04 "Educational attainment"
label variable hv109_05 "Educational attainment"
label variable hv109_06 "Educational attainment"
label variable hv109_07 "Educational attainment"
label variable hv109_08 "Educational attainment"
label variable hv109_09 "Educational attainment"
label variable hv109_10 "Educational attainment"
label variable hv109_11 "Educational attainment"
label variable hv109_12 "Educational attainment"
label variable hv109_13 "Educational attainment"
label variable hv109_14 "Educational attainment"
label variable hv109_15 "Educational attainment"
label variable hv109_16 "Educational attainment"
label variable hv109_17 "Educational attainment"
label variable hv109_18 "Educational attainment"
label variable hv109_19 "Educational attainment"
label variable hv109_20 "Educational attainment"
label variable hv110_01 "Member still in school"
label variable hv110_02 "Member still in school"
label variable hv110_03 "Member still in school"
label variable hv110_04 "Member still in school"
label variable hv110_05 "Member still in school"
label variable hv110_06 "Member still in school"
label variable hv110_07 "Member still in school"
label variable hv110_08 "Member still in school"
label variable hv110_09 "Member still in school"
label variable hv110_10 "Member still in school"
label variable hv110_11 "Member still in school"
label variable hv110_12 "Member still in school"
label variable hv110_13 "Member still in school"
label variable hv110_14 "Member still in school"
label variable hv110_15 "Member still in school"
label variable hv110_16 "Member still in school"
label variable hv110_17 "Member still in school"
label variable hv110_18 "Member still in school"
label variable hv110_19 "Member still in school"
label variable hv110_20 "Member still in school"
label variable hv111_01 "Mother alive"
label variable hv111_02 "Mother alive"
label variable hv111_03 "Mother alive"
label variable hv111_04 "Mother alive"
label variable hv111_05 "Mother alive"
label variable hv111_06 "Mother alive"
label variable hv111_07 "Mother alive"
label variable hv111_08 "Mother alive"
label variable hv111_09 "Mother alive"
label variable hv111_10 "Mother alive"
label variable hv111_11 "Mother alive"
label variable hv111_12 "Mother alive"
label variable hv111_13 "Mother alive"
label variable hv111_14 "Mother alive"
label variable hv111_15 "Mother alive"
label variable hv111_16 "Mother alive"
label variable hv111_17 "Mother alive"
label variable hv111_18 "Mother alive"
label variable hv111_19 "Mother alive"
label variable hv111_20 "Mother alive"
label variable hv112_01 "Mother's line number"
label variable hv112_02 "Mother's line number"
label variable hv112_03 "Mother's line number"
label variable hv112_04 "Mother's line number"
label variable hv112_05 "Mother's line number"
label variable hv112_06 "Mother's line number"
label variable hv112_07 "Mother's line number"
label variable hv112_08 "Mother's line number"
label variable hv112_09 "Mother's line number"
label variable hv112_10 "Mother's line number"
label variable hv112_11 "Mother's line number"
label variable hv112_12 "Mother's line number"
label variable hv112_13 "Mother's line number"
label variable hv112_14 "Mother's line number"
label variable hv112_15 "Mother's line number"
label variable hv112_16 "Mother's line number"
label variable hv112_17 "Mother's line number"
label variable hv112_18 "Mother's line number"
label variable hv112_19 "Mother's line number"
label variable hv112_20 "Mother's line number"
label variable hv113_01 "Father alive"
label variable hv113_02 "Father alive"
label variable hv113_03 "Father alive"
label variable hv113_04 "Father alive"
label variable hv113_05 "Father alive"
label variable hv113_06 "Father alive"
label variable hv113_07 "Father alive"
label variable hv113_08 "Father alive"
label variable hv113_09 "Father alive"
label variable hv113_10 "Father alive"
label variable hv113_11 "Father alive"
label variable hv113_12 "Father alive"
label variable hv113_13 "Father alive"
label variable hv113_14 "Father alive"
label variable hv113_15 "Father alive"
label variable hv113_16 "Father alive"
label variable hv113_17 "Father alive"
label variable hv113_18 "Father alive"
label variable hv113_19 "Father alive"
label variable hv113_20 "Father alive"
label variable hv114_01 "Father's line number"
label variable hv114_02 "Father's line number"
label variable hv114_03 "Father's line number"
label variable hv114_04 "Father's line number"
label variable hv114_05 "Father's line number"
label variable hv114_06 "Father's line number"
label variable hv114_07 "Father's line number"
label variable hv114_08 "Father's line number"
label variable hv114_09 "Father's line number"
label variable hv114_10 "Father's line number"
label variable hv114_11 "Father's line number"
label variable hv114_12 "Father's line number"
label variable hv114_13 "Father's line number"
label variable hv114_14 "Father's line number"
label variable hv114_15 "Father's line number"
label variable hv114_16 "Father's line number"
label variable hv114_17 "Father's line number"
label variable hv114_18 "Father's line number"
label variable hv114_19 "Father's line number"
label variable hv114_20 "Father's line number"
label variable hv115_01 "Current marital status    -NA"
label variable hv115_02 "Current marital status    -NA"
label variable hv115_03 "Current marital status    -NA"
label variable hv115_04 "Current marital status    -NA"
label variable hv115_05 "Current marital status    -NA"
label variable hv115_06 "Current marital status    -NA"
label variable hv115_07 "Current marital status    -NA"
label variable hv115_08 "Current marital status    -NA"
label variable hv115_09 "Current marital status    -NA"
label variable hv115_10 "Current marital status    -NA"
label variable hv115_11 "Current marital status    -NA"
label variable hv115_12 "Current marital status    -NA"
label variable hv115_13 "Current marital status    -NA"
label variable hv115_14 "Current marital status    -NA"
label variable hv115_15 "Current marital status    -NA"
label variable hv115_16 "Current marital status    -NA"
label variable hv115_17 "Current marital status    -NA"
label variable hv115_18 "Current marital status    -NA"
label variable hv115_19 "Current marital status    -NA"
label variable hv115_20 "Current marital status    -NA"
label variable hv116_01 "Currently, formerly, never-NA"
label variable hv116_02 "Currently, formerly, never-NA"
label variable hv116_03 "Currently, formerly, never-NA"
label variable hv116_04 "Currently, formerly, never-NA"
label variable hv116_05 "Currently, formerly, never-NA"
label variable hv116_06 "Currently, formerly, never-NA"
label variable hv116_07 "Currently, formerly, never-NA"
label variable hv116_08 "Currently, formerly, never-NA"
label variable hv116_09 "Currently, formerly, never-NA"
label variable hv116_10 "Currently, formerly, never-NA"
label variable hv116_11 "Currently, formerly, never-NA"
label variable hv116_12 "Currently, formerly, never-NA"
label variable hv116_13 "Currently, formerly, never-NA"
label variable hv116_14 "Currently, formerly, never-NA"
label variable hv116_15 "Currently, formerly, never-NA"
label variable hv116_16 "Currently, formerly, never-NA"
label variable hv116_17 "Currently, formerly, never-NA"
label variable hv116_18 "Currently, formerly, never-NA"
label variable hv116_19 "Currently, formerly, never-NA"
label variable hv116_20 "Currently, formerly, never-NA"
label variable hv117_01 "Eligibility for female intview"
label variable hv117_02 "Eligibility for female intview"
label variable hv117_03 "Eligibility for female intview"
label variable hv117_04 "Eligibility for female intview"
label variable hv117_05 "Eligibility for female intview"
label variable hv117_06 "Eligibility for female intview"
label variable hv117_07 "Eligibility for female intview"
label variable hv117_08 "Eligibility for female intview"
label variable hv117_09 "Eligibility for female intview"
label variable hv117_10 "Eligibility for female intview"
label variable hv117_11 "Eligibility for female intview"
label variable hv117_12 "Eligibility for female intview"
label variable hv117_13 "Eligibility for female intview"
label variable hv117_14 "Eligibility for female intview"
label variable hv117_15 "Eligibility for female intview"
label variable hv117_16 "Eligibility for female intview"
label variable hv117_17 "Eligibility for female intview"
label variable hv117_18 "Eligibility for female intview"
label variable hv117_19 "Eligibility for female intview"
label variable hv117_20 "Eligibility for female intview"
label variable hv118_01 "Eligibility for male interview"
label variable hv118_02 "Eligibility for male interview"
label variable hv118_03 "Eligibility for male interview"
label variable hv118_04 "Eligibility for male interview"
label variable hv118_05 "Eligibility for male interview"
label variable hv118_06 "Eligibility for male interview"
label variable hv118_07 "Eligibility for male interview"
label variable hv118_08 "Eligibility for male interview"
label variable hv118_09 "Eligibility for male interview"
label variable hv118_10 "Eligibility for male interview"
label variable hv118_11 "Eligibility for male interview"
label variable hv118_12 "Eligibility for male interview"
label variable hv118_13 "Eligibility for male interview"
label variable hv118_14 "Eligibility for male interview"
label variable hv118_15 "Eligibility for male interview"
label variable hv118_16 "Eligibility for male interview"
label variable hv118_17 "Eligibility for male interview"
label variable hv118_18 "Eligibility for male interview"
label variable hv118_19 "Eligibility for male interview"
label variable hv118_20 "Eligibility for male interview"
label variable hv120_01 "Children eligibility for height/weight and hemoglobin"
label variable hv120_02 "Children eligibility for height/weight and hemoglobin"
label variable hv120_03 "Children eligibility for height/weight and hemoglobin"
label variable hv120_04 "Children eligibility for height/weight and hemoglobin"
label variable hv120_05 "Children eligibility for height/weight and hemoglobin"
label variable hv120_06 "Children eligibility for height/weight and hemoglobin"
label variable hv120_07 "Children eligibility for height/weight and hemoglobin"
label variable hv120_08 "Children eligibility for height/weight and hemoglobin"
label variable hv120_09 "Children eligibility for height/weight and hemoglobin"
label variable hv120_10 "Children eligibility for height/weight and hemoglobin"
label variable hv120_11 "Children eligibility for height/weight and hemoglobin"
label variable hv120_12 "Children eligibility for height/weight and hemoglobin"
label variable hv120_13 "Children eligibility for height/weight and hemoglobin"
label variable hv120_14 "Children eligibility for height/weight and hemoglobin"
label variable hv120_15 "Children eligibility for height/weight and hemoglobin"
label variable hv120_16 "Children eligibility for height/weight and hemoglobin"
label variable hv120_17 "Children eligibility for height/weight and hemoglobin"
label variable hv120_18 "Children eligibility for height/weight and hemoglobin"
label variable hv120_19 "Children eligibility for height/weight and hemoglobin"
label variable hv120_20 "Children eligibility for height/weight and hemoglobin"
label variable hv121_01 "Member attended school during current school year"
label variable hv121_02 "Member attended school during current school year"
label variable hv121_03 "Member attended school during current school year"
label variable hv121_04 "Member attended school during current school year"
label variable hv121_05 "Member attended school during current school year"
label variable hv121_06 "Member attended school during current school year"
label variable hv121_07 "Member attended school during current school year"
label variable hv121_08 "Member attended school during current school year"
label variable hv121_09 "Member attended school during current school year"
label variable hv121_10 "Member attended school during current school year"
label variable hv121_11 "Member attended school during current school year"
label variable hv121_12 "Member attended school during current school year"
label variable hv121_13 "Member attended school during current school year"
label variable hv121_14 "Member attended school during current school year"
label variable hv121_15 "Member attended school during current school year"
label variable hv121_16 "Member attended school during current school year"
label variable hv121_17 "Member attended school during current school year"
label variable hv121_18 "Member attended school during current school year"
label variable hv121_19 "Member attended school during current school year"
label variable hv121_20 "Member attended school during current school year"
label variable hv122_01 "Educational level during current school year"
label variable hv122_02 "Educational level during current school year"
label variable hv122_03 "Educational level during current school year"
label variable hv122_04 "Educational level during current school year"
label variable hv122_05 "Educational level during current school year"
label variable hv122_06 "Educational level during current school year"
label variable hv122_07 "Educational level during current school year"
label variable hv122_08 "Educational level during current school year"
label variable hv122_09 "Educational level during current school year"
label variable hv122_10 "Educational level during current school year"
label variable hv122_11 "Educational level during current school year"
label variable hv122_12 "Educational level during current school year"
label variable hv122_13 "Educational level during current school year"
label variable hv122_14 "Educational level during current school year"
label variable hv122_15 "Educational level during current school year"
label variable hv122_16 "Educational level during current school year"
label variable hv122_17 "Educational level during current school year"
label variable hv122_18 "Educational level during current school year"
label variable hv122_19 "Educational level during current school year"
label variable hv122_20 "Educational level during current school year"
label variable hv123_01 "Grade of education during current school year"
label variable hv123_02 "Grade of education during current school year"
label variable hv123_03 "Grade of education during current school year"
label variable hv123_04 "Grade of education during current school year"
label variable hv123_05 "Grade of education during current school year"
label variable hv123_06 "Grade of education during current school year"
label variable hv123_07 "Grade of education during current school year"
label variable hv123_08 "Grade of education during current school year"
label variable hv123_09 "Grade of education during current school year"
label variable hv123_10 "Grade of education during current school year"
label variable hv123_11 "Grade of education during current school year"
label variable hv123_12 "Grade of education during current school year"
label variable hv123_13 "Grade of education during current school year"
label variable hv123_14 "Grade of education during current school year"
label variable hv123_15 "Grade of education during current school year"
label variable hv123_16 "Grade of education during current school year"
label variable hv123_17 "Grade of education during current school year"
label variable hv123_18 "Grade of education during current school year"
label variable hv123_19 "Grade of education during current school year"
label variable hv123_20 "Grade of education during current school year"
label variable hv124_01 "Education in single years - current school year"
label variable hv124_02 "Education in single years - current school year"
label variable hv124_03 "Education in single years - current school year"
label variable hv124_04 "Education in single years - current school year"
label variable hv124_05 "Education in single years - current school year"
label variable hv124_06 "Education in single years - current school year"
label variable hv124_07 "Education in single years - current school year"
label variable hv124_08 "Education in single years - current school year"
label variable hv124_09 "Education in single years - current school year"
label variable hv124_10 "Education in single years - current school year"
label variable hv124_11 "Education in single years - current school year"
label variable hv124_12 "Education in single years - current school year"
label variable hv124_13 "Education in single years - current school year"
label variable hv124_14 "Education in single years - current school year"
label variable hv124_15 "Education in single years - current school year"
label variable hv124_16 "Education in single years - current school year"
label variable hv124_17 "Education in single years - current school year"
label variable hv124_18 "Education in single years - current school year"
label variable hv124_19 "Education in single years - current school year"
label variable hv124_20 "Education in single years - current school year"
label variable hv125_01 "Member attended school during previous school year"
label variable hv125_02 "Member attended school during previous school year"
label variable hv125_03 "Member attended school during previous school year"
label variable hv125_04 "Member attended school during previous school year"
label variable hv125_05 "Member attended school during previous school year"
label variable hv125_06 "Member attended school during previous school year"
label variable hv125_07 "Member attended school during previous school year"
label variable hv125_08 "Member attended school during previous school year"
label variable hv125_09 "Member attended school during previous school year"
label variable hv125_10 "Member attended school during previous school year"
label variable hv125_11 "Member attended school during previous school year"
label variable hv125_12 "Member attended school during previous school year"
label variable hv125_13 "Member attended school during previous school year"
label variable hv125_14 "Member attended school during previous school year"
label variable hv125_15 "Member attended school during previous school year"
label variable hv125_16 "Member attended school during previous school year"
label variable hv125_17 "Member attended school during previous school year"
label variable hv125_18 "Member attended school during previous school year"
label variable hv125_19 "Member attended school during previous school year"
label variable hv125_20 "Member attended school during previous school year"
label variable hv126_01 "Educational level during previous school year"
label variable hv126_02 "Educational level during previous school year"
label variable hv126_03 "Educational level during previous school year"
label variable hv126_04 "Educational level during previous school year"
label variable hv126_05 "Educational level during previous school year"
label variable hv126_06 "Educational level during previous school year"
label variable hv126_07 "Educational level during previous school year"
label variable hv126_08 "Educational level during previous school year"
label variable hv126_09 "Educational level during previous school year"
label variable hv126_10 "Educational level during previous school year"
label variable hv126_11 "Educational level during previous school year"
label variable hv126_12 "Educational level during previous school year"
label variable hv126_13 "Educational level during previous school year"
label variable hv126_14 "Educational level during previous school year"
label variable hv126_15 "Educational level during previous school year"
label variable hv126_16 "Educational level during previous school year"
label variable hv126_17 "Educational level during previous school year"
label variable hv126_18 "Educational level during previous school year"
label variable hv126_19 "Educational level during previous school year"
label variable hv126_20 "Educational level during previous school year"
label variable hv127_01 "Grade of education during previous school year"
label variable hv127_02 "Grade of education during previous school year"
label variable hv127_03 "Grade of education during previous school year"
label variable hv127_04 "Grade of education during previous school year"
label variable hv127_05 "Grade of education during previous school year"
label variable hv127_06 "Grade of education during previous school year"
label variable hv127_07 "Grade of education during previous school year"
label variable hv127_08 "Grade of education during previous school year"
label variable hv127_09 "Grade of education during previous school year"
label variable hv127_10 "Grade of education during previous school year"
label variable hv127_11 "Grade of education during previous school year"
label variable hv127_12 "Grade of education during previous school year"
label variable hv127_13 "Grade of education during previous school year"
label variable hv127_14 "Grade of education during previous school year"
label variable hv127_15 "Grade of education during previous school year"
label variable hv127_16 "Grade of education during previous school year"
label variable hv127_17 "Grade of education during previous school year"
label variable hv127_18 "Grade of education during previous school year"
label variable hv127_19 "Grade of education during previous school year"
label variable hv127_20 "Grade of education during previous school year"
label variable hv128_01 "Education in single years - previous school year"
label variable hv128_02 "Education in single years - previous school year"
label variable hv128_03 "Education in single years - previous school year"
label variable hv128_04 "Education in single years - previous school year"
label variable hv128_05 "Education in single years - previous school year"
label variable hv128_06 "Education in single years - previous school year"
label variable hv128_07 "Education in single years - previous school year"
label variable hv128_08 "Education in single years - previous school year"
label variable hv128_09 "Education in single years - previous school year"
label variable hv128_10 "Education in single years - previous school year"
label variable hv128_11 "Education in single years - previous school year"
label variable hv128_12 "Education in single years - previous school year"
label variable hv128_13 "Education in single years - previous school year"
label variable hv128_14 "Education in single years - previous school year"
label variable hv128_15 "Education in single years - previous school year"
label variable hv128_16 "Education in single years - previous school year"
label variable hv128_17 "Education in single years - previous school year"
label variable hv128_18 "Education in single years - previous school year"
label variable hv128_19 "Education in single years - previous school year"
label variable hv128_20 "Education in single years - previous school year"
label variable hv129_01 "School attendance status"
label variable hv129_02 "School attendance status"
label variable hv129_03 "School attendance status"
label variable hv129_04 "School attendance status"
label variable hv129_05 "School attendance status"
label variable hv129_06 "School attendance status"
label variable hv129_07 "School attendance status"
label variable hv129_08 "School attendance status"
label variable hv129_09 "School attendance status"
label variable hv129_10 "School attendance status"
label variable hv129_11 "School attendance status"
label variable hv129_12 "School attendance status"
label variable hv129_13 "School attendance status"
label variable hv129_14 "School attendance status"
label variable hv129_15 "School attendance status"
label variable hv129_16 "School attendance status"
label variable hv129_17 "School attendance status"
label variable hv129_18 "School attendance status"
label variable hv129_19 "School attendance status"
label variable hv129_20 "School attendance status"
label variable idxh4_01 "Index to household schedule"
label variable idxh4_02 "Index to household schedule"
label variable idxh4_03 "Index to household schedule"
label variable idxh4_04 "Index to household schedule"
label variable idxh4_05 "Index to household schedule"
label variable idxh4_06 "Index to household schedule"
label variable idxh4_07 "Index to household schedule"
label variable idxh4_08 "Index to household schedule"
label variable idxh4_09 "Index to household schedule"
label variable idxh4_10 "Index to household schedule"
label variable idxh4_11 "Index to household schedule"
label variable idxh4_12 "Index to household schedule"
label variable idxh4_13 "Index to household schedule"
label variable idxh4_14 "Index to household schedule"
label variable idxh4_15 "Index to household schedule"
label variable idxh4_16 "Index to household schedule"
label variable idxh4_17 "Index to household schedule"
label variable idxh4_18 "Index to household schedule"
label variable idxh4_19 "Index to household schedule"
label variable idxh4_20 "Index to household schedule"
label variable sh03_01  "Relationship to head (CS)"
label variable sh03_02  "Relationship to head (CS)"
label variable sh03_03  "Relationship to head (CS)"
label variable sh03_04  "Relationship to head (CS)"
label variable sh03_05  "Relationship to head (CS)"
label variable sh03_06  "Relationship to head (CS)"
label variable sh03_07  "Relationship to head (CS)"
label variable sh03_08  "Relationship to head (CS)"
label variable sh03_09  "Relationship to head (CS)"
label variable sh03_10  "Relationship to head (CS)"
label variable sh03_11  "Relationship to head (CS)"
label variable sh03_12  "Relationship to head (CS)"
label variable sh03_13  "Relationship to head (CS)"
label variable sh03_14  "Relationship to head (CS)"
label variable sh03_15  "Relationship to head (CS)"
label variable sh03_16  "Relationship to head (CS)"
label variable sh03_17  "Relationship to head (CS)"
label variable sh03_18  "Relationship to head (CS)"
label variable sh03_19  "Relationship to head (CS)"
label variable sh03_20  "Relationship to head (CS)"
label variable sh15a_01 "Education level (CS)"
label variable sh15a_02 "Education level (CS)"
label variable sh15a_03 "Education level (CS)"
label variable sh15a_04 "Education level (CS)"
label variable sh15a_05 "Education level (CS)"
label variable sh15a_06 "Education level (CS)"
label variable sh15a_07 "Education level (CS)"
label variable sh15a_08 "Education level (CS)"
label variable sh15a_09 "Education level (CS)"
label variable sh15a_10 "Education level (CS)"
label variable sh15a_11 "Education level (CS)"
label variable sh15a_12 "Education level (CS)"
label variable sh15a_13 "Education level (CS)"
label variable sh15a_14 "Education level (CS)"
label variable sh15a_15 "Education level (CS)"
label variable sh15a_16 "Education level (CS)"
label variable sh15a_17 "Education level (CS)"
label variable sh15a_18 "Education level (CS)"
label variable sh15a_19 "Education level (CS)"
label variable sh15a_20 "Education level (CS)"
label variable sh16_01  "Currently attending school (CS)"
label variable sh16_02  "Currently attending school (CS)"
label variable sh16_03  "Currently attending school (CS)"
label variable sh16_04  "Currently attending school (CS)"
label variable sh16_05  "Currently attending school (CS)"
label variable sh16_06  "Currently attending school (CS)"
label variable sh16_07  "Currently attending school (CS)"
label variable sh16_08  "Currently attending school (CS)"
label variable sh16_09  "Currently attending school (CS)"
label variable sh16_10  "Currently attending school (CS)"
label variable sh16_11  "Currently attending school (CS)"
label variable sh16_12  "Currently attending school (CS)"
label variable sh16_13  "Currently attending school (CS)"
label variable sh16_14  "Currently attending school (CS)"
label variable sh16_15  "Currently attending school (CS)"
label variable sh16_16  "Currently attending school (CS)"
label variable sh16_17  "Currently attending school (CS)"
label variable sh16_18  "Currently attending school (CS)"
label variable sh16_19  "Currently attending school (CS)"
label variable sh16_20  "Currently attending school (CS)"
label variable sh17_01  "Member attended school during current school year (CS)"
label variable sh17_02  "Member attended school during current school year (CS)"
label variable sh17_03  "Member attended school during current school year (CS)"
label variable sh17_04  "Member attended school during current school year (CS)"
label variable sh17_05  "Member attended school during current school year (CS)"
label variable sh17_06  "Member attended school during current school year (CS)"
label variable sh17_07  "Member attended school during current school year (CS)"
label variable sh17_08  "Member attended school during current school year (CS)"
label variable sh17_09  "Member attended school during current school year (CS)"
label variable sh17_10  "Member attended school during current school year (CS)"
label variable sh17_11  "Member attended school during current school year (CS)"
label variable sh17_12  "Member attended school during current school year (CS)"
label variable sh17_13  "Member attended school during current school year (CS)"
label variable sh17_14  "Member attended school during current school year (CS)"
label variable sh17_15  "Member attended school during current school year (CS)"
label variable sh17_16  "Member attended school during current school year (CS)"
label variable sh17_17  "Member attended school during current school year (CS)"
label variable sh17_18  "Member attended school during current school year (CS)"
label variable sh17_19  "Member attended school during current school year (CS)"
label variable sh17_20  "Member attended school during current school year (CS)"
label variable sh18a_01 "Education level (CS)"
label variable sh18a_02 "Education level (CS)"
label variable sh18a_03 "Education level (CS)"
label variable sh18a_04 "Education level (CS)"
label variable sh18a_05 "Education level (CS)"
label variable sh18a_06 "Education level (CS)"
label variable sh18a_07 "Education level (CS)"
label variable sh18a_08 "Education level (CS)"
label variable sh18a_09 "Education level (CS)"
label variable sh18a_10 "Education level (CS)"
label variable sh18a_11 "Education level (CS)"
label variable sh18a_12 "Education level (CS)"
label variable sh18a_13 "Education level (CS)"
label variable sh18a_14 "Education level (CS)"
label variable sh18a_15 "Education level (CS)"
label variable sh18a_16 "Education level (CS)"
label variable sh18a_17 "Education level (CS)"
label variable sh18a_18 "Education level (CS)"
label variable sh18a_19 "Education level (CS)"
label variable sh18a_20 "Education level (CS)"
label variable sh18b_01 "Highest class"
label variable sh18b_02 "Highest class"
label variable sh18b_03 "Highest class"
label variable sh18b_04 "Highest class"
label variable sh18b_05 "Highest class"
label variable sh18b_06 "Highest class"
label variable sh18b_07 "Highest class"
label variable sh18b_08 "Highest class"
label variable sh18b_09 "Highest class"
label variable sh18b_10 "Highest class"
label variable sh18b_11 "Highest class"
label variable sh18b_12 "Highest class"
label variable sh18b_13 "Highest class"
label variable sh18b_14 "Highest class"
label variable sh18b_15 "Highest class"
label variable sh18b_16 "Highest class"
label variable sh18b_17 "Highest class"
label variable sh18b_18 "Highest class"
label variable sh18b_19 "Highest class"
label variable sh18b_20 "Highest class"
label variable sh19_01  "Attended school in previous academic year (CS)"
label variable sh19_02  "Attended school in previous academic year (CS)"
label variable sh19_03  "Attended school in previous academic year (CS)"
label variable sh19_04  "Attended school in previous academic year (CS)"
label variable sh19_05  "Attended school in previous academic year (CS)"
label variable sh19_06  "Attended school in previous academic year (CS)"
label variable sh19_07  "Attended school in previous academic year (CS)"
label variable sh19_08  "Attended school in previous academic year (CS)"
label variable sh19_09  "Attended school in previous academic year (CS)"
label variable sh19_10  "Attended school in previous academic year (CS)"
label variable sh19_11  "Attended school in previous academic year (CS)"
label variable sh19_12  "Attended school in previous academic year (CS)"
label variable sh19_13  "Attended school in previous academic year (CS)"
label variable sh19_14  "Attended school in previous academic year (CS)"
label variable sh19_15  "Attended school in previous academic year (CS)"
label variable sh19_16  "Attended school in previous academic year (CS)"
label variable sh19_17  "Attended school in previous academic year (CS)"
label variable sh19_18  "Attended school in previous academic year (CS)"
label variable sh19_19  "Attended school in previous academic year (CS)"
label variable sh19_20  "Attended school in previous academic year (CS)"
label variable sh20a_01 "Education level (CS) in preceding year"
label variable sh20a_02 "Education level (CS) in preceding year"
label variable sh20a_03 "Education level (CS) in preceding year"
label variable sh20a_04 "Education level (CS) in preceding year"
label variable sh20a_05 "Education level (CS) in preceding year"
label variable sh20a_06 "Education level (CS) in preceding year"
label variable sh20a_07 "Education level (CS) in preceding year"
label variable sh20a_08 "Education level (CS) in preceding year"
label variable sh20a_09 "Education level (CS) in preceding year"
label variable sh20a_10 "Education level (CS) in preceding year"
label variable sh20a_11 "Education level (CS) in preceding year"
label variable sh20a_12 "Education level (CS) in preceding year"
label variable sh20a_13 "Education level (CS) in preceding year"
label variable sh20a_14 "Education level (CS) in preceding year"
label variable sh20a_15 "Education level (CS) in preceding year"
label variable sh20a_16 "Education level (CS) in preceding year"
label variable sh20a_17 "Education level (CS) in preceding year"
label variable sh20a_18 "Education level (CS) in preceding year"
label variable sh20a_19 "Education level (CS) in preceding year"
label variable sh20a_20 "Education level (CS) in preceding year"
label variable sh20b_01 "Highest class (CS) preceding year"
label variable sh20b_02 "Highest class (CS) preceding year"
label variable sh20b_03 "Highest class (CS) preceding year"
label variable sh20b_04 "Highest class (CS) preceding year"
label variable sh20b_05 "Highest class (CS) preceding year"
label variable sh20b_06 "Highest class (CS) preceding year"
label variable sh20b_07 "Highest class (CS) preceding year"
label variable sh20b_08 "Highest class (CS) preceding year"
label variable sh20b_09 "Highest class (CS) preceding year"
label variable sh20b_10 "Highest class (CS) preceding year"
label variable sh20b_11 "Highest class (CS) preceding year"
label variable sh20b_12 "Highest class (CS) preceding year"
label variable sh20b_13 "Highest class (CS) preceding year"
label variable sh20b_14 "Highest class (CS) preceding year"
label variable sh20b_15 "Highest class (CS) preceding year"
label variable sh20b_16 "Highest class (CS) preceding year"
label variable sh20b_17 "Highest class (CS) preceding year"
label variable sh20b_18 "Highest class (CS) preceding year"
label variable sh20b_19 "Highest class (CS) preceding year"
label variable sh20b_20 "Highest class (CS) preceding year"
label variable ha0_01   "Index to household schedule"
label variable ha0_02   "Index to household schedule"
label variable ha0_03   "Index to household schedule"
label variable ha0_04   "Index to household schedule"
label variable ha0_05   "Index to household schedule"
label variable ha0_06   "Index to household schedule"
label variable ha0_07   "Index to household schedule"
label variable ha0_08   "Index to household schedule"
label variable ha0_09   "Index to household schedule"
label variable ha0_10   "Index to household schedule"
label variable ha0_11   "Index to household schedule"
label variable ha0_12   "Index to household schedule"
label variable ha0_13   "Index to household schedule"
label variable ha0_14   "Index to household schedule"
label variable ha0_15   "Index to household schedule"
label variable ha1_01   "Women's age in years"
label variable ha1_02   "Women's age in years"
label variable ha1_03   "Women's age in years"
label variable ha1_04   "Women's age in years"
label variable ha1_05   "Women's age in years"
label variable ha1_06   "Women's age in years"
label variable ha1_07   "Women's age in years"
label variable ha1_08   "Women's age in years"
label variable ha1_09   "Women's age in years"
label variable ha1_10   "Women's age in years"
label variable ha1_11   "Women's age in years"
label variable ha1_12   "Women's age in years"
label variable ha1_13   "Women's age in years"
label variable ha1_14   "Women's age in years"
label variable ha1_15   "Women's age in years"
label variable ha2_01   "Respondent's weight (kilos-1d)"
label variable ha2_02   "Respondent's weight (kilos-1d)"
label variable ha2_03   "Respondent's weight (kilos-1d)"
label variable ha2_04   "Respondent's weight (kilos-1d)"
label variable ha2_05   "Respondent's weight (kilos-1d)"
label variable ha2_06   "Respondent's weight (kilos-1d)"
label variable ha2_07   "Respondent's weight (kilos-1d)"
label variable ha2_08   "Respondent's weight (kilos-1d)"
label variable ha2_09   "Respondent's weight (kilos-1d)"
label variable ha2_10   "Respondent's weight (kilos-1d)"
label variable ha2_11   "Respondent's weight (kilos-1d)"
label variable ha2_12   "Respondent's weight (kilos-1d)"
label variable ha2_13   "Respondent's weight (kilos-1d)"
label variable ha2_14   "Respondent's weight (kilos-1d)"
label variable ha2_15   "Respondent's weight (kilos-1d)"
label variable ha3_01   "Respondent's height (cms-1d)"
label variable ha3_02   "Respondent's height (cms-1d)"
label variable ha3_03   "Respondent's height (cms-1d)"
label variable ha3_04   "Respondent's height (cms-1d)"
label variable ha3_05   "Respondent's height (cms-1d)"
label variable ha3_06   "Respondent's height (cms-1d)"
label variable ha3_07   "Respondent's height (cms-1d)"
label variable ha3_08   "Respondent's height (cms-1d)"
label variable ha3_09   "Respondent's height (cms-1d)"
label variable ha3_10   "Respondent's height (cms-1d)"
label variable ha3_11   "Respondent's height (cms-1d)"
label variable ha3_12   "Respondent's height (cms-1d)"
label variable ha3_13   "Respondent's height (cms-1d)"
label variable ha3_14   "Respondent's height (cms-1d)"
label variable ha3_15   "Respondent's height (cms-1d)"
label variable ha4_01   "Ht/A Percentile (resp.)"
label variable ha4_02   "Ht/A Percentile (resp.)"
label variable ha4_03   "Ht/A Percentile (resp.)"
label variable ha4_04   "Ht/A Percentile (resp.)"
label variable ha4_05   "Ht/A Percentile (resp.)"
label variable ha4_06   "Ht/A Percentile (resp.)"
label variable ha4_07   "Ht/A Percentile (resp.)"
label variable ha4_08   "Ht/A Percentile (resp.)"
label variable ha4_09   "Ht/A Percentile (resp.)"
label variable ha4_10   "Ht/A Percentile (resp.)"
label variable ha4_11   "Ht/A Percentile (resp.)"
label variable ha4_12   "Ht/A Percentile (resp.)"
label variable ha4_13   "Ht/A Percentile (resp.)"
label variable ha4_14   "Ht/A Percentile (resp.)"
label variable ha4_15   "Ht/A Percentile (resp.)"
label variable ha5_01   "Ht/A Standard deviations (resp"
label variable ha5_02   "Ht/A Standard deviations (resp"
label variable ha5_03   "Ht/A Standard deviations (resp"
label variable ha5_04   "Ht/A Standard deviations (resp"
label variable ha5_05   "Ht/A Standard deviations (resp"
label variable ha5_06   "Ht/A Standard deviations (resp"
label variable ha5_07   "Ht/A Standard deviations (resp"
label variable ha5_08   "Ht/A Standard deviations (resp"
label variable ha5_09   "Ht/A Standard deviations (resp"
label variable ha5_10   "Ht/A Standard deviations (resp"
label variable ha5_11   "Ht/A Standard deviations (resp"
label variable ha5_12   "Ht/A Standard deviations (resp"
label variable ha5_13   "Ht/A Standard deviations (resp"
label variable ha5_14   "Ht/A Standard deviations (resp"
label variable ha5_15   "Ht/A Standard deviations (resp"
label variable ha6_01   "Ht/A Percent ref. median (resp"
label variable ha6_02   "Ht/A Percent ref. median (resp"
label variable ha6_03   "Ht/A Percent ref. median (resp"
label variable ha6_04   "Ht/A Percent ref. median (resp"
label variable ha6_05   "Ht/A Percent ref. median (resp"
label variable ha6_06   "Ht/A Percent ref. median (resp"
label variable ha6_07   "Ht/A Percent ref. median (resp"
label variable ha6_08   "Ht/A Percent ref. median (resp"
label variable ha6_09   "Ht/A Percent ref. median (resp"
label variable ha6_10   "Ht/A Percent ref. median (resp"
label variable ha6_11   "Ht/A Percent ref. median (resp"
label variable ha6_12   "Ht/A Percent ref. median (resp"
label variable ha6_13   "Ht/A Percent ref. median (resp"
label variable ha6_14   "Ht/A Percent ref. median (resp"
label variable ha6_15   "Ht/A Percent ref. median (resp"
label variable ha11_01  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_02  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_03  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_04  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_05  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_06  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_07  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_08  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_09  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_10  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_11  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_12  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_13  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_14  "Wt/Ht Std deviations(resp) DHS"
label variable ha11_15  "Wt/Ht Std deviations(resp) DHS"
label variable ha12_01  "Wt/Ht Percent ref. median (DHS"
label variable ha12_02  "Wt/Ht Percent ref. median (DHS"
label variable ha12_03  "Wt/Ht Percent ref. median (DHS"
label variable ha12_04  "Wt/Ht Percent ref. median (DHS"
label variable ha12_05  "Wt/Ht Percent ref. median (DHS"
label variable ha12_06  "Wt/Ht Percent ref. median (DHS"
label variable ha12_07  "Wt/Ht Percent ref. median (DHS"
label variable ha12_08  "Wt/Ht Percent ref. median (DHS"
label variable ha12_09  "Wt/Ht Percent ref. median (DHS"
label variable ha12_10  "Wt/Ht Percent ref. median (DHS"
label variable ha12_11  "Wt/Ht Percent ref. median (DHS"
label variable ha12_12  "Wt/Ht Percent ref. median (DHS"
label variable ha12_13  "Wt/Ht Percent ref. median (DHS"
label variable ha12_14  "Wt/Ht Percent ref. median (DHS"
label variable ha12_15  "Wt/Ht Percent ref. median (DHS"
label variable ha12a_01 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_02 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_03 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_04 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_05 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_06 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_07 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_08 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_09 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_10 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_11 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_12 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_13 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_14 "Wt/Ht Percent ref. median (Fog"
label variable ha12a_15 "Wt/Ht Percent ref. median (Fog"
label variable ha12b_01 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_02 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_03 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_04 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_05 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_06 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_07 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_08 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_09 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_10 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_11 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_12 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_13 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_14 "Wt/Ht Percent ref. median (WHO"
label variable ha12b_15 "Wt/Ht Percent ref. median (WHO"
label variable ha13_01  "Result of measurement of resp."
label variable ha13_02  "Result of measurement of resp."
label variable ha13_03  "Result of measurement of resp."
label variable ha13_04  "Result of measurement of resp."
label variable ha13_05  "Result of measurement of resp."
label variable ha13_06  "Result of measurement of resp."
label variable ha13_07  "Result of measurement of resp."
label variable ha13_08  "Result of measurement of resp."
label variable ha13_09  "Result of measurement of resp."
label variable ha13_10  "Result of measurement of resp."
label variable ha13_11  "Result of measurement of resp."
label variable ha13_12  "Result of measurement of resp."
label variable ha13_13  "Result of measurement of resp."
label variable ha13_14  "Result of measurement of resp."
label variable ha13_15  "Result of measurement of resp."
label variable ha32_01  "Date of birth (cmc)"
label variable ha32_02  "Date of birth (cmc)"
label variable ha32_03  "Date of birth (cmc)"
label variable ha32_04  "Date of birth (cmc)"
label variable ha32_05  "Date of birth (cmc)"
label variable ha32_06  "Date of birth (cmc)"
label variable ha32_07  "Date of birth (cmc)"
label variable ha32_08  "Date of birth (cmc)"
label variable ha32_09  "Date of birth (cmc)"
label variable ha32_10  "Date of birth (cmc)"
label variable ha32_11  "Date of birth (cmc)"
label variable ha32_12  "Date of birth (cmc)"
label variable ha32_13  "Date of birth (cmc)"
label variable ha32_14  "Date of birth (cmc)"
label variable ha32_15  "Date of birth (cmc)"
label variable ha33_01  "Completeness of information"
label variable ha33_02  "Completeness of information"
label variable ha33_03  "Completeness of information"
label variable ha33_04  "Completeness of information"
label variable ha33_05  "Completeness of information"
label variable ha33_06  "Completeness of information"
label variable ha33_07  "Completeness of information"
label variable ha33_08  "Completeness of information"
label variable ha33_09  "Completeness of information"
label variable ha33_10  "Completeness of information"
label variable ha33_11  "Completeness of information"
label variable ha33_12  "Completeness of information"
label variable ha33_13  "Completeness of information"
label variable ha33_14  "Completeness of information"
label variable ha33_15  "Completeness of information"
label variable ha35_01  "Smoking                   -NA"
label variable ha35_02  "Smoking                   -NA"
label variable ha35_03  "Smoking                   -NA"
label variable ha35_04  "Smoking                   -NA"
label variable ha35_05  "Smoking                   -NA"
label variable ha35_06  "Smoking                   -NA"
label variable ha35_07  "Smoking                   -NA"
label variable ha35_08  "Smoking                   -NA"
label variable ha35_09  "Smoking                   -NA"
label variable ha35_10  "Smoking                   -NA"
label variable ha35_11  "Smoking                   -NA"
label variable ha35_12  "Smoking                   -NA"
label variable ha35_13  "Smoking                   -NA"
label variable ha35_14  "Smoking                   -NA"
label variable ha35_15  "Smoking                   -NA"
label variable ha40_01  "Body mass index for respondent"
label variable ha40_02  "Body mass index for respondent"
label variable ha40_03  "Body mass index for respondent"
label variable ha40_04  "Body mass index for respondent"
label variable ha40_05  "Body mass index for respondent"
label variable ha40_06  "Body mass index for respondent"
label variable ha40_07  "Body mass index for respondent"
label variable ha40_08  "Body mass index for respondent"
label variable ha40_09  "Body mass index for respondent"
label variable ha40_10  "Body mass index for respondent"
label variable ha40_11  "Body mass index for respondent"
label variable ha40_12  "Body mass index for respondent"
label variable ha40_13  "Body mass index for respondent"
label variable ha40_14  "Body mass index for respondent"
label variable ha40_15  "Body mass index for respondent"
label variable ha41_01  "Rohrer's index for respondent"
label variable ha41_02  "Rohrer's index for respondent"
label variable ha41_03  "Rohrer's index for respondent"
label variable ha41_04  "Rohrer's index for respondent"
label variable ha41_05  "Rohrer's index for respondent"
label variable ha41_06  "Rohrer's index for respondent"
label variable ha41_07  "Rohrer's index for respondent"
label variable ha41_08  "Rohrer's index for respondent"
label variable ha41_09  "Rohrer's index for respondent"
label variable ha41_10  "Rohrer's index for respondent"
label variable ha41_11  "Rohrer's index for respondent"
label variable ha41_12  "Rohrer's index for respondent"
label variable ha41_13  "Rohrer's index for respondent"
label variable ha41_14  "Rohrer's index for respondent"
label variable ha41_15  "Rohrer's index for respondent"
label variable ha50_01  "Under age 18              -NA"
label variable ha50_02  "Under age 18              -NA"
label variable ha50_03  "Under age 18              -NA"
label variable ha50_04  "Under age 18              -NA"
label variable ha50_05  "Under age 18              -NA"
label variable ha50_06  "Under age 18              -NA"
label variable ha50_07  "Under age 18              -NA"
label variable ha50_08  "Under age 18              -NA"
label variable ha50_09  "Under age 18              -NA"
label variable ha50_10  "Under age 18              -NA"
label variable ha50_11  "Under age 18              -NA"
label variable ha50_12  "Under age 18              -NA"
label variable ha50_13  "Under age 18              -NA"
label variable ha50_14  "Under age 18              -NA"
label variable ha50_15  "Under age 18              -NA"
label variable ha51_01  "Line no. of parent/caretak-NA"
label variable ha51_02  "Line no. of parent/caretak-NA"
label variable ha51_03  "Line no. of parent/caretak-NA"
label variable ha51_04  "Line no. of parent/caretak-NA"
label variable ha51_05  "Line no. of parent/caretak-NA"
label variable ha51_06  "Line no. of parent/caretak-NA"
label variable ha51_07  "Line no. of parent/caretak-NA"
label variable ha51_08  "Line no. of parent/caretak-NA"
label variable ha51_09  "Line no. of parent/caretak-NA"
label variable ha51_10  "Line no. of parent/caretak-NA"
label variable ha51_11  "Line no. of parent/caretak-NA"
label variable ha51_12  "Line no. of parent/caretak-NA"
label variable ha51_13  "Line no. of parent/caretak-NA"
label variable ha51_14  "Line no. of parent/caretak-NA"
label variable ha51_15  "Line no. of parent/caretak-NA"
label variable ha52_01  "Read consent statement    -NA"
label variable ha52_02  "Read consent statement    -NA"
label variable ha52_03  "Read consent statement    -NA"
label variable ha52_04  "Read consent statement    -NA"
label variable ha52_05  "Read consent statement    -NA"
label variable ha52_06  "Read consent statement    -NA"
label variable ha52_07  "Read consent statement    -NA"
label variable ha52_08  "Read consent statement    -NA"
label variable ha52_09  "Read consent statement    -NA"
label variable ha52_10  "Read consent statement    -NA"
label variable ha52_11  "Read consent statement    -NA"
label variable ha52_12  "Read consent statement    -NA"
label variable ha52_13  "Read consent statement    -NA"
label variable ha52_14  "Read consent statement    -NA"
label variable ha52_15  "Read consent statement    -NA"
label variable ha53_01  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_02  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_03  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_04  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_05  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_06  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_07  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_08  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_09  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_10  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_11  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_12  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_13  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_14  "Hemoglobin level (g/dl - 1-NA"
label variable ha53_15  "Hemoglobin level (g/dl - 1-NA"
label variable ha54_01  "Currently pregnant        -NA"
label variable ha54_02  "Currently pregnant        -NA"
label variable ha54_03  "Currently pregnant        -NA"
label variable ha54_04  "Currently pregnant        -NA"
label variable ha54_05  "Currently pregnant        -NA"
label variable ha54_06  "Currently pregnant        -NA"
label variable ha54_07  "Currently pregnant        -NA"
label variable ha54_08  "Currently pregnant        -NA"
label variable ha54_09  "Currently pregnant        -NA"
label variable ha54_10  "Currently pregnant        -NA"
label variable ha54_11  "Currently pregnant        -NA"
label variable ha54_12  "Currently pregnant        -NA"
label variable ha54_13  "Currently pregnant        -NA"
label variable ha54_14  "Currently pregnant        -NA"
label variable ha54_15  "Currently pregnant        -NA"
label variable ha55_01  "Result of measuring (Hemog-NA"
label variable ha55_02  "Result of measuring (Hemog-NA"
label variable ha55_03  "Result of measuring (Hemog-NA"
label variable ha55_04  "Result of measuring (Hemog-NA"
label variable ha55_05  "Result of measuring (Hemog-NA"
label variable ha55_06  "Result of measuring (Hemog-NA"
label variable ha55_07  "Result of measuring (Hemog-NA"
label variable ha55_08  "Result of measuring (Hemog-NA"
label variable ha55_09  "Result of measuring (Hemog-NA"
label variable ha55_10  "Result of measuring (Hemog-NA"
label variable ha55_11  "Result of measuring (Hemog-NA"
label variable ha55_12  "Result of measuring (Hemog-NA"
label variable ha55_13  "Result of measuring (Hemog-NA"
label variable ha55_14  "Result of measuring (Hemog-NA"
label variable ha55_15  "Result of measuring (Hemog-NA"
label variable ha56_01  "Hemoglobin level adjusted -NA"
label variable ha56_02  "Hemoglobin level adjusted -NA"
label variable ha56_03  "Hemoglobin level adjusted -NA"
label variable ha56_04  "Hemoglobin level adjusted -NA"
label variable ha56_05  "Hemoglobin level adjusted -NA"
label variable ha56_06  "Hemoglobin level adjusted -NA"
label variable ha56_07  "Hemoglobin level adjusted -NA"
label variable ha56_08  "Hemoglobin level adjusted -NA"
label variable ha56_09  "Hemoglobin level adjusted -NA"
label variable ha56_10  "Hemoglobin level adjusted -NA"
label variable ha56_11  "Hemoglobin level adjusted -NA"
label variable ha56_12  "Hemoglobin level adjusted -NA"
label variable ha56_13  "Hemoglobin level adjusted -NA"
label variable ha56_14  "Hemoglobin level adjusted -NA"
label variable ha56_15  "Hemoglobin level adjusted -NA"
label variable ha57_01  "Anemia level              -NA"
label variable ha57_02  "Anemia level              -NA"
label variable ha57_03  "Anemia level              -NA"
label variable ha57_04  "Anemia level              -NA"
label variable ha57_05  "Anemia level              -NA"
label variable ha57_06  "Anemia level              -NA"
label variable ha57_07  "Anemia level              -NA"
label variable ha57_08  "Anemia level              -NA"
label variable ha57_09  "Anemia level              -NA"
label variable ha57_10  "Anemia level              -NA"
label variable ha57_11  "Anemia level              -NA"
label variable ha57_12  "Anemia level              -NA"
label variable ha57_13  "Anemia level              -NA"
label variable ha57_14  "Anemia level              -NA"
label variable ha57_15  "Anemia level              -NA"
label variable ha58_01  "Agrees to referral        -NA"
label variable ha58_02  "Agrees to referral        -NA"
label variable ha58_03  "Agrees to referral        -NA"
label variable ha58_04  "Agrees to referral        -NA"
label variable ha58_05  "Agrees to referral        -NA"
label variable ha58_06  "Agrees to referral        -NA"
label variable ha58_07  "Agrees to referral        -NA"
label variable ha58_08  "Agrees to referral        -NA"
label variable ha58_09  "Agrees to referral        -NA"
label variable ha58_10  "Agrees to referral        -NA"
label variable ha58_11  "Agrees to referral        -NA"
label variable ha58_12  "Agrees to referral        -NA"
label variable ha58_13  "Agrees to referral        -NA"
label variable ha58_14  "Agrees to referral        -NA"
label variable ha58_15  "Agrees to referral        -NA"
label variable hc0_01   "Index to household schedule"
label variable hc0_02   "Index to household schedule"
label variable hc0_03   "Index to household schedule"
label variable hc0_04   "Index to household schedule"
label variable hc0_05   "Index to household schedule"
label variable hc0_06   "Index to household schedule"
label variable hc0_07   "Index to household schedule"
label variable hc0_08   "Index to household schedule"
label variable hc0_09   "Index to household schedule"
label variable hc0_10   "Index to household schedule"
label variable hc0_11   "Index to household schedule"
label variable hc0_12   "Index to household schedule"
label variable hc0_13   "Index to household schedule"
label variable hc0_14   "Index to household schedule"
label variable hc0_15   "Index to household schedule"
label variable hc1_01   "Age in months"
label variable hc1_02   "Age in months"
label variable hc1_03   "Age in months"
label variable hc1_04   "Age in months"
label variable hc1_05   "Age in months"
label variable hc1_06   "Age in months"
label variable hc1_07   "Age in months"
label variable hc1_08   "Age in months"
label variable hc1_09   "Age in months"
label variable hc1_10   "Age in months"
label variable hc1_11   "Age in months"
label variable hc1_12   "Age in months"
label variable hc1_13   "Age in months"
label variable hc1_14   "Age in months"
label variable hc1_15   "Age in months"
label variable hc2_01   "Weight in kilograms (1 dec.)"
label variable hc2_02   "Weight in kilograms (1 dec.)"
label variable hc2_03   "Weight in kilograms (1 dec.)"
label variable hc2_04   "Weight in kilograms (1 dec.)"
label variable hc2_05   "Weight in kilograms (1 dec.)"
label variable hc2_06   "Weight in kilograms (1 dec.)"
label variable hc2_07   "Weight in kilograms (1 dec.)"
label variable hc2_08   "Weight in kilograms (1 dec.)"
label variable hc2_09   "Weight in kilograms (1 dec.)"
label variable hc2_10   "Weight in kilograms (1 dec.)"
label variable hc2_11   "Weight in kilograms (1 dec.)"
label variable hc2_12   "Weight in kilograms (1 dec.)"
label variable hc2_13   "Weight in kilograms (1 dec.)"
label variable hc2_14   "Weight in kilograms (1 dec.)"
label variable hc2_15   "Weight in kilograms (1 dec.)"
label variable hc3_01   "Height in centimeters (1 dec.)"
label variable hc3_02   "Height in centimeters (1 dec.)"
label variable hc3_03   "Height in centimeters (1 dec.)"
label variable hc3_04   "Height in centimeters (1 dec.)"
label variable hc3_05   "Height in centimeters (1 dec.)"
label variable hc3_06   "Height in centimeters (1 dec.)"
label variable hc3_07   "Height in centimeters (1 dec.)"
label variable hc3_08   "Height in centimeters (1 dec.)"
label variable hc3_09   "Height in centimeters (1 dec.)"
label variable hc3_10   "Height in centimeters (1 dec.)"
label variable hc3_11   "Height in centimeters (1 dec.)"
label variable hc3_12   "Height in centimeters (1 dec.)"
label variable hc3_13   "Height in centimeters (1 dec.)"
label variable hc3_14   "Height in centimeters (1 dec.)"
label variable hc3_15   "Height in centimeters (1 dec.)"
label variable hc4_01   "Ht/A Percentile"
label variable hc4_02   "Ht/A Percentile"
label variable hc4_03   "Ht/A Percentile"
label variable hc4_04   "Ht/A Percentile"
label variable hc4_05   "Ht/A Percentile"
label variable hc4_06   "Ht/A Percentile"
label variable hc4_07   "Ht/A Percentile"
label variable hc4_08   "Ht/A Percentile"
label variable hc4_09   "Ht/A Percentile"
label variable hc4_10   "Ht/A Percentile"
label variable hc4_11   "Ht/A Percentile"
label variable hc4_12   "Ht/A Percentile"
label variable hc4_13   "Ht/A Percentile"
label variable hc4_14   "Ht/A Percentile"
label variable hc4_15   "Ht/A Percentile"
label variable hc5_01   "Ht/A Standard deviations"
label variable hc5_02   "Ht/A Standard deviations"
label variable hc5_03   "Ht/A Standard deviations"
label variable hc5_04   "Ht/A Standard deviations"
label variable hc5_05   "Ht/A Standard deviations"
label variable hc5_06   "Ht/A Standard deviations"
label variable hc5_07   "Ht/A Standard deviations"
label variable hc5_08   "Ht/A Standard deviations"
label variable hc5_09   "Ht/A Standard deviations"
label variable hc5_10   "Ht/A Standard deviations"
label variable hc5_11   "Ht/A Standard deviations"
label variable hc5_12   "Ht/A Standard deviations"
label variable hc5_13   "Ht/A Standard deviations"
label variable hc5_14   "Ht/A Standard deviations"
label variable hc5_15   "Ht/A Standard deviations"
label variable hc6_01   "Ht/A Percent of ref. median"
label variable hc6_02   "Ht/A Percent of ref. median"
label variable hc6_03   "Ht/A Percent of ref. median"
label variable hc6_04   "Ht/A Percent of ref. median"
label variable hc6_05   "Ht/A Percent of ref. median"
label variable hc6_06   "Ht/A Percent of ref. median"
label variable hc6_07   "Ht/A Percent of ref. median"
label variable hc6_08   "Ht/A Percent of ref. median"
label variable hc6_09   "Ht/A Percent of ref. median"
label variable hc6_10   "Ht/A Percent of ref. median"
label variable hc6_11   "Ht/A Percent of ref. median"
label variable hc6_12   "Ht/A Percent of ref. median"
label variable hc6_13   "Ht/A Percent of ref. median"
label variable hc6_14   "Ht/A Percent of ref. median"
label variable hc6_15   "Ht/A Percent of ref. median"
label variable hc7_01   "Wt/A Percentile"
label variable hc7_02   "Wt/A Percentile"
label variable hc7_03   "Wt/A Percentile"
label variable hc7_04   "Wt/A Percentile"
label variable hc7_05   "Wt/A Percentile"
label variable hc7_06   "Wt/A Percentile"
label variable hc7_07   "Wt/A Percentile"
label variable hc7_08   "Wt/A Percentile"
label variable hc7_09   "Wt/A Percentile"
label variable hc7_10   "Wt/A Percentile"
label variable hc7_11   "Wt/A Percentile"
label variable hc7_12   "Wt/A Percentile"
label variable hc7_13   "Wt/A Percentile"
label variable hc7_14   "Wt/A Percentile"
label variable hc7_15   "Wt/A Percentile"
label variable hc8_01   "Wt/A Standard deviations"
label variable hc8_02   "Wt/A Standard deviations"
label variable hc8_03   "Wt/A Standard deviations"
label variable hc8_04   "Wt/A Standard deviations"
label variable hc8_05   "Wt/A Standard deviations"
label variable hc8_06   "Wt/A Standard deviations"
label variable hc8_07   "Wt/A Standard deviations"
label variable hc8_08   "Wt/A Standard deviations"
label variable hc8_09   "Wt/A Standard deviations"
label variable hc8_10   "Wt/A Standard deviations"
label variable hc8_11   "Wt/A Standard deviations"
label variable hc8_12   "Wt/A Standard deviations"
label variable hc8_13   "Wt/A Standard deviations"
label variable hc8_14   "Wt/A Standard deviations"
label variable hc8_15   "Wt/A Standard deviations"
label variable hc9_01   "Wt/A Percent of ref. median"
label variable hc9_02   "Wt/A Percent of ref. median"
label variable hc9_03   "Wt/A Percent of ref. median"
label variable hc9_04   "Wt/A Percent of ref. median"
label variable hc9_05   "Wt/A Percent of ref. median"
label variable hc9_06   "Wt/A Percent of ref. median"
label variable hc9_07   "Wt/A Percent of ref. median"
label variable hc9_08   "Wt/A Percent of ref. median"
label variable hc9_09   "Wt/A Percent of ref. median"
label variable hc9_10   "Wt/A Percent of ref. median"
label variable hc9_11   "Wt/A Percent of ref. median"
label variable hc9_12   "Wt/A Percent of ref. median"
label variable hc9_13   "Wt/A Percent of ref. median"
label variable hc9_14   "Wt/A Percent of ref. median"
label variable hc9_15   "Wt/A Percent of ref. median"
label variable hc10_01  "Wt/Ht Percentile"
label variable hc10_02  "Wt/Ht Percentile"
label variable hc10_03  "Wt/Ht Percentile"
label variable hc10_04  "Wt/Ht Percentile"
label variable hc10_05  "Wt/Ht Percentile"
label variable hc10_06  "Wt/Ht Percentile"
label variable hc10_07  "Wt/Ht Percentile"
label variable hc10_08  "Wt/Ht Percentile"
label variable hc10_09  "Wt/Ht Percentile"
label variable hc10_10  "Wt/Ht Percentile"
label variable hc10_11  "Wt/Ht Percentile"
label variable hc10_12  "Wt/Ht Percentile"
label variable hc10_13  "Wt/Ht Percentile"
label variable hc10_14  "Wt/Ht Percentile"
label variable hc10_15  "Wt/Ht Percentile"
label variable hc11_01  "Wt/Ht Standard deviations"
label variable hc11_02  "Wt/Ht Standard deviations"
label variable hc11_03  "Wt/Ht Standard deviations"
label variable hc11_04  "Wt/Ht Standard deviations"
label variable hc11_05  "Wt/Ht Standard deviations"
label variable hc11_06  "Wt/Ht Standard deviations"
label variable hc11_07  "Wt/Ht Standard deviations"
label variable hc11_08  "Wt/Ht Standard deviations"
label variable hc11_09  "Wt/Ht Standard deviations"
label variable hc11_10  "Wt/Ht Standard deviations"
label variable hc11_11  "Wt/Ht Standard deviations"
label variable hc11_12  "Wt/Ht Standard deviations"
label variable hc11_13  "Wt/Ht Standard deviations"
label variable hc11_14  "Wt/Ht Standard deviations"
label variable hc11_15  "Wt/Ht Standard deviations"
label variable hc12_01  "Wt/Ht Percent of ref. median"
label variable hc12_02  "Wt/Ht Percent of ref. median"
label variable hc12_03  "Wt/Ht Percent of ref. median"
label variable hc12_04  "Wt/Ht Percent of ref. median"
label variable hc12_05  "Wt/Ht Percent of ref. median"
label variable hc12_06  "Wt/Ht Percent of ref. median"
label variable hc12_07  "Wt/Ht Percent of ref. median"
label variable hc12_08  "Wt/Ht Percent of ref. median"
label variable hc12_09  "Wt/Ht Percent of ref. median"
label variable hc12_10  "Wt/Ht Percent of ref. median"
label variable hc12_11  "Wt/Ht Percent of ref. median"
label variable hc12_12  "Wt/Ht Percent of ref. median"
label variable hc12_13  "Wt/Ht Percent of ref. median"
label variable hc12_14  "Wt/Ht Percent of ref. median"
label variable hc12_15  "Wt/Ht Percent of ref. median"
label variable hc13_01  "Reason not measured"
label variable hc13_02  "Reason not measured"
label variable hc13_03  "Reason not measured"
label variable hc13_04  "Reason not measured"
label variable hc13_05  "Reason not measured"
label variable hc13_06  "Reason not measured"
label variable hc13_07  "Reason not measured"
label variable hc13_08  "Reason not measured"
label variable hc13_09  "Reason not measured"
label variable hc13_10  "Reason not measured"
label variable hc13_11  "Reason not measured"
label variable hc13_12  "Reason not measured"
label variable hc13_13  "Reason not measured"
label variable hc13_14  "Reason not measured"
label variable hc13_15  "Reason not measured"
label variable hc15_01  "Height: lying or standing"
label variable hc15_02  "Height: lying or standing"
label variable hc15_03  "Height: lying or standing"
label variable hc15_04  "Height: lying or standing"
label variable hc15_05  "Height: lying or standing"
label variable hc15_06  "Height: lying or standing"
label variable hc15_07  "Height: lying or standing"
label variable hc15_08  "Height: lying or standing"
label variable hc15_09  "Height: lying or standing"
label variable hc15_10  "Height: lying or standing"
label variable hc15_11  "Height: lying or standing"
label variable hc15_12  "Height: lying or standing"
label variable hc15_13  "Height: lying or standing"
label variable hc15_14  "Height: lying or standing"
label variable hc15_15  "Height: lying or standing"
label variable hc16_01  "Day of birth of child"
label variable hc16_02  "Day of birth of child"
label variable hc16_03  "Day of birth of child"
label variable hc16_04  "Day of birth of child"
label variable hc16_05  "Day of birth of child"
label variable hc16_06  "Day of birth of child"
label variable hc16_07  "Day of birth of child"
label variable hc16_08  "Day of birth of child"
label variable hc16_09  "Day of birth of child"
label variable hc16_10  "Day of birth of child"
label variable hc16_11  "Day of birth of child"
label variable hc16_12  "Day of birth of child"
label variable hc16_13  "Day of birth of child"
label variable hc16_14  "Day of birth of child"
label variable hc16_15  "Day of birth of child"
label variable hc17_01  "Date measured (day)"
label variable hc17_02  "Date measured (day)"
label variable hc17_03  "Date measured (day)"
label variable hc17_04  "Date measured (day)"
label variable hc17_05  "Date measured (day)"
label variable hc17_06  "Date measured (day)"
label variable hc17_07  "Date measured (day)"
label variable hc17_08  "Date measured (day)"
label variable hc17_09  "Date measured (day)"
label variable hc17_10  "Date measured (day)"
label variable hc17_11  "Date measured (day)"
label variable hc17_12  "Date measured (day)"
label variable hc17_13  "Date measured (day)"
label variable hc17_14  "Date measured (day)"
label variable hc17_15  "Date measured (day)"
label variable hc18_01  "Date measured (month)"
label variable hc18_02  "Date measured (month)"
label variable hc18_03  "Date measured (month)"
label variable hc18_04  "Date measured (month)"
label variable hc18_05  "Date measured (month)"
label variable hc18_06  "Date measured (month)"
label variable hc18_07  "Date measured (month)"
label variable hc18_08  "Date measured (month)"
label variable hc18_09  "Date measured (month)"
label variable hc18_10  "Date measured (month)"
label variable hc18_11  "Date measured (month)"
label variable hc18_12  "Date measured (month)"
label variable hc18_13  "Date measured (month)"
label variable hc18_14  "Date measured (month)"
label variable hc18_15  "Date measured (month)"
label variable hc19_01  "Date measured (year)"
label variable hc19_02  "Date measured (year)"
label variable hc19_03  "Date measured (year)"
label variable hc19_04  "Date measured (year)"
label variable hc19_05  "Date measured (year)"
label variable hc19_06  "Date measured (year)"
label variable hc19_07  "Date measured (year)"
label variable hc19_08  "Date measured (year)"
label variable hc19_09  "Date measured (year)"
label variable hc19_10  "Date measured (year)"
label variable hc19_11  "Date measured (year)"
label variable hc19_12  "Date measured (year)"
label variable hc19_13  "Date measured (year)"
label variable hc19_14  "Date measured (year)"
label variable hc19_15  "Date measured (year)"
label variable hc27_01  "Sex"
label variable hc27_02  "Sex"
label variable hc27_03  "Sex"
label variable hc27_04  "Sex"
label variable hc27_05  "Sex"
label variable hc27_06  "Sex"
label variable hc27_07  "Sex"
label variable hc27_08  "Sex"
label variable hc27_09  "Sex"
label variable hc27_10  "Sex"
label variable hc27_11  "Sex"
label variable hc27_12  "Sex"
label variable hc27_13  "Sex"
label variable hc27_14  "Sex"
label variable hc27_15  "Sex"
label variable hc30_01  "Month of birth of child"
label variable hc30_02  "Month of birth of child"
label variable hc30_03  "Month of birth of child"
label variable hc30_04  "Month of birth of child"
label variable hc30_05  "Month of birth of child"
label variable hc30_06  "Month of birth of child"
label variable hc30_07  "Month of birth of child"
label variable hc30_08  "Month of birth of child"
label variable hc30_09  "Month of birth of child"
label variable hc30_10  "Month of birth of child"
label variable hc30_11  "Month of birth of child"
label variable hc30_12  "Month of birth of child"
label variable hc30_13  "Month of birth of child"
label variable hc30_14  "Month of birth of child"
label variable hc30_15  "Month of birth of child"
label variable hc31_01  "Year of birth of child"
label variable hc31_02  "Year of birth of child"
label variable hc31_03  "Year of birth of child"
label variable hc31_04  "Year of birth of child"
label variable hc31_05  "Year of birth of child"
label variable hc31_06  "Year of birth of child"
label variable hc31_07  "Year of birth of child"
label variable hc31_08  "Year of birth of child"
label variable hc31_09  "Year of birth of child"
label variable hc31_10  "Year of birth of child"
label variable hc31_11  "Year of birth of child"
label variable hc31_12  "Year of birth of child"
label variable hc31_13  "Year of birth of child"
label variable hc31_14  "Year of birth of child"
label variable hc31_15  "Year of birth of child"
label variable hc32_01  "Date of birth (cmc)"
label variable hc32_02  "Date of birth (cmc)"
label variable hc32_03  "Date of birth (cmc)"
label variable hc32_04  "Date of birth (cmc)"
label variable hc32_05  "Date of birth (cmc)"
label variable hc32_06  "Date of birth (cmc)"
label variable hc32_07  "Date of birth (cmc)"
label variable hc32_08  "Date of birth (cmc)"
label variable hc32_09  "Date of birth (cmc)"
label variable hc32_10  "Date of birth (cmc)"
label variable hc32_11  "Date of birth (cmc)"
label variable hc32_12  "Date of birth (cmc)"
label variable hc32_13  "Date of birth (cmc)"
label variable hc32_14  "Date of birth (cmc)"
label variable hc32_15  "Date of birth (cmc)"
label variable hc33_01  "Completeness of information"
label variable hc33_02  "Completeness of information"
label variable hc33_03  "Completeness of information"
label variable hc33_04  "Completeness of information"
label variable hc33_05  "Completeness of information"
label variable hc33_06  "Completeness of information"
label variable hc33_07  "Completeness of information"
label variable hc33_08  "Completeness of information"
label variable hc33_09  "Completeness of information"
label variable hc33_10  "Completeness of information"
label variable hc33_11  "Completeness of information"
label variable hc33_12  "Completeness of information"
label variable hc33_13  "Completeness of information"
label variable hc33_14  "Completeness of information"
label variable hc33_15  "Completeness of information"
label variable hc51_01  "Line no. of parent/caretak-NA"
label variable hc51_02  "Line no. of parent/caretak-NA"
label variable hc51_03  "Line no. of parent/caretak-NA"
label variable hc51_04  "Line no. of parent/caretak-NA"
label variable hc51_05  "Line no. of parent/caretak-NA"
label variable hc51_06  "Line no. of parent/caretak-NA"
label variable hc51_07  "Line no. of parent/caretak-NA"
label variable hc51_08  "Line no. of parent/caretak-NA"
label variable hc51_09  "Line no. of parent/caretak-NA"
label variable hc51_10  "Line no. of parent/caretak-NA"
label variable hc51_11  "Line no. of parent/caretak-NA"
label variable hc51_12  "Line no. of parent/caretak-NA"
label variable hc51_13  "Line no. of parent/caretak-NA"
label variable hc51_14  "Line no. of parent/caretak-NA"
label variable hc51_15  "Line no. of parent/caretak-NA"
label variable hc52_01  "Read consent statement    -NA"
label variable hc52_02  "Read consent statement    -NA"
label variable hc52_03  "Read consent statement    -NA"
label variable hc52_04  "Read consent statement    -NA"
label variable hc52_05  "Read consent statement    -NA"
label variable hc52_06  "Read consent statement    -NA"
label variable hc52_07  "Read consent statement    -NA"
label variable hc52_08  "Read consent statement    -NA"
label variable hc52_09  "Read consent statement    -NA"
label variable hc52_10  "Read consent statement    -NA"
label variable hc52_11  "Read consent statement    -NA"
label variable hc52_12  "Read consent statement    -NA"
label variable hc52_13  "Read consent statement    -NA"
label variable hc52_14  "Read consent statement    -NA"
label variable hc52_15  "Read consent statement    -NA"
label variable hc53_01  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_02  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_03  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_04  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_05  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_06  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_07  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_08  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_09  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_10  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_11  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_12  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_13  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_14  "Hemoglobin level (g/dl - 1-NA"
label variable hc53_15  "Hemoglobin level (g/dl - 1-NA"
label variable hc55_01  "Result of measuring (Hemog-NA"
label variable hc55_02  "Result of measuring (Hemog-NA"
label variable hc55_03  "Result of measuring (Hemog-NA"
label variable hc55_04  "Result of measuring (Hemog-NA"
label variable hc55_05  "Result of measuring (Hemog-NA"
label variable hc55_06  "Result of measuring (Hemog-NA"
label variable hc55_07  "Result of measuring (Hemog-NA"
label variable hc55_08  "Result of measuring (Hemog-NA"
label variable hc55_09  "Result of measuring (Hemog-NA"
label variable hc55_10  "Result of measuring (Hemog-NA"
label variable hc55_11  "Result of measuring (Hemog-NA"
label variable hc55_12  "Result of measuring (Hemog-NA"
label variable hc55_13  "Result of measuring (Hemog-NA"
label variable hc55_14  "Result of measuring (Hemog-NA"
label variable hc55_15  "Result of measuring (Hemog-NA"
label variable hc56_01  "Hemoglobin level adjusted -NA"
label variable hc56_02  "Hemoglobin level adjusted -NA"
label variable hc56_03  "Hemoglobin level adjusted -NA"
label variable hc56_04  "Hemoglobin level adjusted -NA"
label variable hc56_05  "Hemoglobin level adjusted -NA"
label variable hc56_06  "Hemoglobin level adjusted -NA"
label variable hc56_07  "Hemoglobin level adjusted -NA"
label variable hc56_08  "Hemoglobin level adjusted -NA"
label variable hc56_09  "Hemoglobin level adjusted -NA"
label variable hc56_10  "Hemoglobin level adjusted -NA"
label variable hc56_11  "Hemoglobin level adjusted -NA"
label variable hc56_12  "Hemoglobin level adjusted -NA"
label variable hc56_13  "Hemoglobin level adjusted -NA"
label variable hc56_14  "Hemoglobin level adjusted -NA"
label variable hc56_15  "Hemoglobin level adjusted -NA"
label variable hc57_01  "Anemia level              -NA"
label variable hc57_02  "Anemia level              -NA"
label variable hc57_03  "Anemia level              -NA"
label variable hc57_04  "Anemia level              -NA"
label variable hc57_05  "Anemia level              -NA"
label variable hc57_06  "Anemia level              -NA"
label variable hc57_07  "Anemia level              -NA"
label variable hc57_08  "Anemia level              -NA"
label variable hc57_09  "Anemia level              -NA"
label variable hc57_10  "Anemia level              -NA"
label variable hc57_11  "Anemia level              -NA"
label variable hc57_12  "Anemia level              -NA"
label variable hc57_13  "Anemia level              -NA"
label variable hc57_14  "Anemia level              -NA"
label variable hc57_15  "Anemia level              -NA"
label variable hc58_01  "Agrees to referral        -NA"
label variable hc58_02  "Agrees to referral        -NA"
label variable hc58_03  "Agrees to referral        -NA"
label variable hc58_04  "Agrees to referral        -NA"
label variable hc58_05  "Agrees to referral        -NA"
label variable hc58_06  "Agrees to referral        -NA"
label variable hc58_07  "Agrees to referral        -NA"
label variable hc58_08  "Agrees to referral        -NA"
label variable hc58_09  "Agrees to referral        -NA"
label variable hc58_10  "Agrees to referral        -NA"
label variable hc58_11  "Agrees to referral        -NA"
label variable hc58_12  "Agrees to referral        -NA"
label variable hc58_13  "Agrees to referral        -NA"
label variable hc58_14  "Agrees to referral        -NA"
label variable hc58_15  "Agrees to referral        -NA"
label variable hc60_01  "Mother's line number if interviewed and defacto"
label variable hc60_02  "Mother's line number if interviewed and defacto"
label variable hc60_03  "Mother's line number if interviewed and defacto"
label variable hc60_04  "Mother's line number if interviewed and defacto"
label variable hc60_05  "Mother's line number if interviewed and defacto"
label variable hc60_06  "Mother's line number if interviewed and defacto"
label variable hc60_07  "Mother's line number if interviewed and defacto"
label variable hc60_08  "Mother's line number if interviewed and defacto"
label variable hc60_09  "Mother's line number if interviewed and defacto"
label variable hc60_10  "Mother's line number if interviewed and defacto"
label variable hc60_11  "Mother's line number if interviewed and defacto"
label variable hc60_12  "Mother's line number if interviewed and defacto"
label variable hc60_13  "Mother's line number if interviewed and defacto"
label variable hc60_14  "Mother's line number if interviewed and defacto"
label variable hc60_15  "Mother's line number if interviewed and defacto"
label variable hc61_01  "Mother's education level"
label variable hc61_02  "Mother's education level"
label variable hc61_03  "Mother's education level"
label variable hc61_04  "Mother's education level"
label variable hc61_05  "Mother's education level"
label variable hc61_06  "Mother's education level"
label variable hc61_07  "Mother's education level"
label variable hc61_08  "Mother's education level"
label variable hc61_09  "Mother's education level"
label variable hc61_10  "Mother's education level"
label variable hc61_11  "Mother's education level"
label variable hc61_12  "Mother's education level"
label variable hc61_13  "Mother's education level"
label variable hc61_14  "Mother's education level"
label variable hc61_15  "Mother's education level"
label variable hc62_01  "Highest year of education"
label variable hc62_02  "Highest year of education"
label variable hc62_03  "Highest year of education"
label variable hc62_04  "Highest year of education"
label variable hc62_05  "Highest year of education"
label variable hc62_06  "Highest year of education"
label variable hc62_07  "Highest year of education"
label variable hc62_08  "Highest year of education"
label variable hc62_09  "Highest year of education"
label variable hc62_10  "Highest year of education"
label variable hc62_11  "Highest year of education"
label variable hc62_12  "Highest year of education"
label variable hc62_13  "Highest year of education"
label variable hc62_14  "Highest year of education"
label variable hc62_15  "Highest year of education"
label variable hc63_01  "Previous birth interval"
label variable hc63_02  "Previous birth interval"
label variable hc63_03  "Previous birth interval"
label variable hc63_04  "Previous birth interval"
label variable hc63_05  "Previous birth interval"
label variable hc63_06  "Previous birth interval"
label variable hc63_07  "Previous birth interval"
label variable hc63_08  "Previous birth interval"
label variable hc63_09  "Previous birth interval"
label variable hc63_10  "Previous birth interval"
label variable hc63_11  "Previous birth interval"
label variable hc63_12  "Previous birth interval"
label variable hc63_13  "Previous birth interval"
label variable hc63_14  "Previous birth interval"
label variable hc63_15  "Previous birth interval"
label variable hc64_01  "Birth order number"
label variable hc64_02  "Birth order number"
label variable hc64_03  "Birth order number"
label variable hc64_04  "Birth order number"
label variable hc64_05  "Birth order number"
label variable hc64_06  "Birth order number"
label variable hc64_07  "Birth order number"
label variable hc64_08  "Birth order number"
label variable hc64_09  "Birth order number"
label variable hc64_10  "Birth order number"
label variable hc64_11  "Birth order number"
label variable hc64_12  "Birth order number"
label variable hc64_13  "Birth order number"
label variable hc64_14  "Birth order number"
label variable hc64_15  "Birth order number"
label variable hc65_01  "Education level (CS)"
label variable hc65_02  "Education level (CS)"
label variable hc65_03  "Education level (CS)"
label variable hc65_04  "Education level (CS)"
label variable hc65_05  "Education level (CS)"
label variable hc65_06  "Education level (CS)"
label variable hc65_07  "Education level (CS)"
label variable hc65_08  "Education level (CS)"
label variable hc65_09  "Education level (CS)"
label variable hc65_10  "Education level (CS)"
label variable hc65_11  "Education level (CS)"
label variable hc65_12  "Education level (CS)"
label variable hc65_13  "Education level (CS)"
label variable hc65_14  "Education level (CS)"
label variable hc65_15  "Education level (CS)"
label variable hc66_01  "Ever participated in a literacy program outside of primary"
label variable hc66_02  "Ever participated in a literacy program outside of primary"
label variable hc66_03  "Ever participated in a literacy program outside of primary"
label variable hc66_04  "Ever participated in a literacy program outside of primary"
label variable hc66_05  "Ever participated in a literacy program outside of primary"
label variable hc66_06  "Ever participated in a literacy program outside of primary"
label variable hc66_07  "Ever participated in a literacy program outside of primary"
label variable hc66_08  "Ever participated in a literacy program outside of primary"
label variable hc66_09  "Ever participated in a literacy program outside of primary"
label variable hc66_10  "Ever participated in a literacy program outside of primary"
label variable hc66_11  "Ever participated in a literacy program outside of primary"
label variable hc66_12  "Ever participated in a literacy program outside of primary"
label variable hc66_13  "Ever participated in a literacy program outside of primary"
label variable hc66_14  "Ever participated in a literacy program outside of primary"
label variable hc66_15  "Ever participated in a literacy program outside of primary"

#delimit ;
label define HV015   
     1 "Completed"
     2 "HH present, no resp"
     3 "HH absent"
     4 "Postponed"
     5 "Refused"
     6 "Dwelling vacant"
     7 "Dwelling destroyed"
     8 "Dwelling not found"
     9 "Other"
;
label define HV018   
   999 "Missing"
;
label define HV019   
    99 "Missing"
;
label define HV020   
     0 "All woman sample"
     1 "Ever married sample"
;
label define HV023   
     0 "Butare - Autre Villes"
     1 "Butare"
     2 "Byumba"
     3 "Cyangugu"
     4 "Gikongoro"
     5 "Gisenyi"
     6 "Gitarama"
     7 "Kibungo"
     8 "Kibuye"
     9 "Kigali Ville (PVK)"
    10 "Kigali Rurale"
    11 "Ruhengeri"
    12 "Umutara"
;
label define HV024   
     1 "Butare"
     2 "Byumba"
     3 "Cyangugu"
     4 "Gikongoro"
     5 "Gisenyi"
     6 "Gitarama"
     7 "Kibungo"
     8 "Kibuye"
     9 "Kigali Ville (PVK)"
    10 "Kigali Rurale"
    11 "Ruhengeri"
    12 "Umutara"
;
label define HV025   
     1 "Urban"
     2 "Rural"
;
label define HV026   
     0 "Kigali"
     1 "Small city"
     2 "Town"
     3 "Countryside"
;
label define HV027   
     0 "Not selected"
     1 "Men's survey"
     2 "Husband's survey"
;
label define HV030   
   999 "Missing"
;
label define HV031   
   999 "Missing"
;
label define HV032   
    99 "Missing"
;
label define HV201   
    10 "PIPED WATER"
    11 "Piped into dwelling"
    12 "Piped into yard/plot"
    13 "Public tap"
    20 "OPEN WELL WATER"
    21 "Open well in dwelling"
    22 "Open well in yard/plot"
    23 "Open public well"
    30 "COVERED WELL/BOREHOLE"
    31 "Protected well in dwelling"
    32 "Protected well in yard/plot"
    33 "Protected public well"
    40 "SURFACE WATER"
    41 "Spring"
    42 "River, stream"
    43 "Pond, lake"
    44 "Dam"
    51 "Rainwater"
    61 "Tanker truck"
    71 "Bottled water"
    96 "Other"
;
label define HV204   
   996 "On premises"
;
label define HV205   
    10 "FLUSH TOILET"
    11 "Flush Toilet"
    20 "PIT TOILET LATRINE"
    21 "Traditional pit toilet"
    22 "Ventilated improved pit (VIP) latrine"
    30 "NO FACILITY"
    31 "No facility"
    96 "OTHER"
;
label define HV206   
     0 "No"
     1 "Yes"
;
label define HV207   
     0 "No"
     1 "Yes"
;
label define HV208   
     0 "No"
     1 "Yes"
;
label define HV209   
     0 "No"
     1 "Yes"
;
label define HV210   
     0 "No"
     1 "Yes"
;
label define HV211   
     0 "No"
     1 "Yes"
;
label define HV212   
     0 "No"
     1 "Yes"
;
label define HV213   
    10 "NATURAL"
    11 "Earth, sand"
    12 "Dung"
    20 "RUDIMENTARY"
    21 "Wood planks"
    22 "Palm/bamboo"
    30 "FINISHED"
    31 "Parquet or polished wood"
    32 "Vinyl or asphalt strips"
    33 "Ceramic tiles"
    34 "Cement"
    35 "Carpet"
    96 "OTHER"
;
label define HV217   
     0 "No adults"
     1 "One adult"
     2 "Two adults, opp. sex"
     3 "Two adults, same sex"
     4 "Three+ related adult"
     5 "Unrelated adults"
;
label define HV219   
     1 "Male"
     2 "Female"
;
label define HV220   
    97 "97+"
    98 "DK"
;
label define HV221   
     0 "No"
     1 "Yes"
;
label define HV225   
     0 "No"
     1 "Yes"
;
label define HV226   
     1 "Electricity"
     2 "LPG, natural gas"
     3 "Biogas"
     4 "Kerosene"
     5 "Coal, lignite"
     6 "Charcoal"
     7 "Firewood, straw"
     8 "Dung"
    96 "Other"
;
label define HV227   
     0 "No"
     1 "Yes"
;
label define HV228   
     0 "No"
     1 "All children"
     2 "Some children"
     3 "No bednet in HH"
;
label define HV230   
     0 "Nowhere"
     1 "In dwelling/yard/plot"
     2 "Somewhere else"
;
label define HV231   
     0 "No"
     1 "Yes"
;
label define HV232   
     0 "No"
     1 "Yes"
;
label define HV233   
     0 "No"
     1 "Yes"
;
label define HV234   
     0 "0 PPM (No Iodine)"
     7 "7 PPM"
    15 "15 PPM"
    30 "30 PPM"
   994 "Salt not tested"
   995 "No salt in household"
;
label define SHINTER 
     0 "No"
     1 "Yes"
;
label define SHLANG  
     1 "Kinyarwanda"
     2 "Other language"
;
label define HV101   
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Co-spouse"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
;
label define HV102   
     0 "No"
     1 "Yes"
;
label define HV103   
     0 "No"
     1 "Yes"
;
label define HV104   
     1 "Male"
     2 "Female"
;
label define HV105   
    97 "97+"
    98 "DK"
;
label define HV106   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV107   
    98 "DK"
;
label define HV108   
    97 "Inconsistent"
    98 "DK"
;
label define HV109   
     0 "No education"
     1 "Incomplete primary"
     2 "Complete primary"
     3 "Incomplete secondary"
     4 "Complete secondary"
     5 "Higher"
     8 "DK"
;
label define HV110   
     0 "No"
     1 "Yes"
;
label define HV111   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV112   
     0 "Mother not in HH"
;
label define HV113   
     0 "No"
     1 "Yes"
     8 "DK"
;
label define HV114   
     0 "Father not in HH"
;
label define HV117   
     0 "Not eligible"
     1 "Eligible"
;
label define HV118   
     0 "Not eligible"
     1 "Eligible"
;
label define HV120   
     0 "Not eligible"
     1 "Eligible"
;
label define HV121   
     0 "No"
     1 "Currently attending"
     2 "Attended at some time"
;
label define HV122   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV123   
    98 "DK"
;
label define HV124   
    97 "Inconsistent"
    98 "DK"
;
label define HV125   
     0 "No"
     1 "Yes"
;
label define HV126   
     0 "No education, preschool"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
     8 "DK"
;
label define HV127   
    98 "DK"
;
label define HV128   
    97 "Inconsistent"
    98 "DK"
;
label define HV129   
     0 "Never attended"
     1 "Entered school"
     2 "Advanced"
     3 "Repeating"
     4 "Dropout"
     5 "Left school 2+ years ago"
     8 "DK"
;
label define SH03    
     1 "Head"
     2 "Wife or husband"
     3 "Son/daughter"
     4 "Son/daughter-in-law"
     5 "Grandchild"
     6 "Parent"
     7 "Parent-in-law"
     8 "Brother/sister"
     9 "Cousin, nephew, niece"
    10 "Other relative"
    11 "Adopted/foster child"
    12 "Not related"
    98 "DK"
;
label define SH15A   
     0 "Maternelle"
     1 "Primaire"
     2 "Primaire rTformT"
     3 "Post-primaire"
     4 "Secondaire"
     5 "SupTrieur"
     8 "DK"
;
label define SH16    
     0 "No"
     1 "Yes"
;
label define SH17    
     0 "No"
     1 "Yes"
;
label define SH18A   
     0 "Maternelle"
     1 "Primaire"
     2 "Primaire rTformT"
     3 "Post-primaire"
     4 "Secondaire"
     5 "SupTrieur"
     8 "DK"
;
label define SH18B   
     0 "< 1 year"
    98 "DK"
;
label define SH19    
     0 "No"
     1 "Yes"
;
label define SH20A   
     0 "Maternelle"
     1 "Primaire"
     2 "Primaire rTformT"
     3 "Post-primaire"
     4 "Secondaire"
     5 "SupTrieur"
     8 "DK"
;
label define SH20B   
     0 "< 1 year"
    98 "DK"
;
label define HA2     
  9999 "Missing"
;
label define HA3     
  9999 "Missing"
;
label define HA4     
  9998 "Flagged cases"
;
label define HA5     
  9998 "Flagged cases"
;
label define HA6     
 99998 "Flagged cases"
;
label define HA11    
  9998 "Flagged cases"
;
label define HA12    
 99998 "Flagged cases"
;
label define HA12A   
 99998 "Flagged cases"
;
label define HA12B   
 99998 "Flagged cases"
;
label define HA13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HA33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HA40    
  9998 "Flagged cases"
;
label define HA41    
  9998 "Flagged cases"
;
label define HC2     
  9999 "Missing"
;
label define HC3     
  9999 "Missing"
;
label define HC4     
  9998 "Flagged cases"
;
label define HC5     
  9998 "Flagged cases"
;
label define HC6     
 99998 "Flagged cases"
;
label define HC7     
  9998 "Flagged cases"
;
label define HC8     
  9998 "Flagged cases"
;
label define HC9     
 99998 "Flagged cases"
;
label define HC10    
  9998 "Flagged cases"
;
label define HC11    
  9998 "Flagged cases"
;
label define HC12    
 99998 "Flagged cases"
;
label define HC13    
     0 "Measured"
     3 "Not present"
     4 "Refused"
     6 "Other"
;
label define HC15    
     1 "Lying"
     2 "Standing"
;
label define HC16    
    99 "Missing"
;
label define HC27    
     1 "Male"
     2 "Female"
;
label define HC30    
    97 "Inconsistent"
    98 "DK"
;
label define HC31    
  9997 "Inconsistent"
  9998 "DK"
;
label define HC33    
     1 "Month and year"
     2 "Month and age -y imp"
     3 "Year and age - m imp"
     4 "Y & age - y ignored"
     5 "Year - a, m imp"
     6 "Age - y, m imp"
     7 "Month - a, y imp"
     8 "None - all imp"
;
label define HC60    
     0 "Mother in hh but not eligible"
   993 "Mother not de facto"
   994 "Incomplete woman's interview"
   995 "Not in household"
   998 "Don't know"
;
label define HC61    
     0 "No education"
     1 "Primary"
     2 "Secondary"
     3 "Higher"
;
label define HC62    
    99 "Missing"
;
label define HC63    
   999 "Missing"
;
label define HC64    
    99 "Missing"
;
label define HC65    
     0 "None, preschool"
     1 "Primary"
     2 "Primaire r?form?"
     3 "Post primary"
     4 "Secondary"
     5 "Higher"
;
label define HC66    
     0 "No"
     1 "Yes"
;

#delimit cr
label values hv015    HV015   
label values hv020    HV020   
label values hv023    HV023   
label values hv024    HV024   
label values hv025    HV025   
label values hv026    HV026   
label values hv027    HV027   
label values hv201    HV201   
label values hv204    HV204   
label values hv205    HV205   
label values hv206    HV206   
label values hv207    HV207   
label values hv208    HV208   
label values hv209    HV209   
label values hv210    HV210   
label values hv211    HV211   
label values hv212    HV212   
label values hv213    HV213   
label values hv217    HV217   
label values hv219    HV219   
label values hv220    HV220   
label values hv221    HV221   
label values hv225    HV225   
label values hv226    HV226   
label values hv227    HV227   
label values hv228    HV228   
label values hv230    HV230   
label values hv231    HV231   
label values hv232    HV232   
label values hv233    HV233   
label values hv234    HV234   
label values shinter  SHINTER 
label values shlang   SHLANG  
label values hv101_01 HV101   
label values hv101_02 HV101   
label values hv101_03 HV101   
label values hv101_04 HV101   
label values hv101_05 HV101   
label values hv101_06 HV101   
label values hv101_07 HV101   
label values hv101_08 HV101   
label values hv101_09 HV101   
label values hv101_10 HV101   
label values hv101_11 HV101   
label values hv101_12 HV101   
label values hv101_13 HV101   
label values hv101_14 HV101   
label values hv101_15 HV101   
label values hv101_16 HV101   
label values hv101_17 HV101   
label values hv101_18 HV101   
label values hv101_19 HV101   
label values hv101_20 HV101   
label values hv102_01 HV102   
label values hv102_02 HV102   
label values hv102_03 HV102   
label values hv102_04 HV102   
label values hv102_05 HV102   
label values hv102_06 HV102   
label values hv102_07 HV102   
label values hv102_08 HV102   
label values hv102_09 HV102   
label values hv102_10 HV102   
label values hv102_11 HV102   
label values hv102_12 HV102   
label values hv102_13 HV102   
label values hv102_14 HV102   
label values hv102_15 HV102   
label values hv102_16 HV102   
label values hv102_17 HV102   
label values hv102_18 HV102   
label values hv102_19 HV102   
label values hv102_20 HV102   
label values hv103_01 HV103   
label values hv103_02 HV103   
label values hv103_03 HV103   
label values hv103_04 HV103   
label values hv103_05 HV103   
label values hv103_06 HV103   
label values hv103_07 HV103   
label values hv103_08 HV103   
label values hv103_09 HV103   
label values hv103_10 HV103   
label values hv103_11 HV103   
label values hv103_12 HV103   
label values hv103_13 HV103   
label values hv103_14 HV103   
label values hv103_15 HV103   
label values hv103_16 HV103   
label values hv103_17 HV103   
label values hv103_18 HV103   
label values hv103_19 HV103   
label values hv103_20 HV103   
label values hv104_01 HV104   
label values hv104_02 HV104   
label values hv104_03 HV104   
label values hv104_04 HV104   
label values hv104_05 HV104   
label values hv104_06 HV104   
label values hv104_07 HV104   
label values hv104_08 HV104   
label values hv104_09 HV104   
label values hv104_10 HV104   
label values hv104_11 HV104   
label values hv104_12 HV104   
label values hv104_13 HV104   
label values hv104_14 HV104   
label values hv104_15 HV104   
label values hv104_16 HV104   
label values hv104_17 HV104   
label values hv104_18 HV104   
label values hv104_19 HV104   
label values hv104_20 HV104   
label values hv105_01 HV105   
label values hv105_02 HV105   
label values hv105_03 HV105   
label values hv105_04 HV105   
label values hv105_05 HV105   
label values hv105_06 HV105   
label values hv105_07 HV105   
label values hv105_08 HV105   
label values hv105_09 HV105   
label values hv105_10 HV105   
label values hv105_11 HV105   
label values hv105_12 HV105   
label values hv105_13 HV105   
label values hv105_14 HV105   
label values hv105_15 HV105   
label values hv105_16 HV105   
label values hv105_17 HV105   
label values hv105_18 HV105   
label values hv105_19 HV105   
label values hv105_20 HV105   
label values hv106_01 HV106   
label values hv106_02 HV106   
label values hv106_03 HV106   
label values hv106_04 HV106   
label values hv106_05 HV106   
label values hv106_06 HV106   
label values hv106_07 HV106   
label values hv106_08 HV106   
label values hv106_09 HV106   
label values hv106_10 HV106   
label values hv106_11 HV106   
label values hv106_12 HV106   
label values hv106_13 HV106   
label values hv106_14 HV106   
label values hv106_15 HV106   
label values hv106_16 HV106   
label values hv106_17 HV106   
label values hv106_18 HV106   
label values hv106_19 HV106   
label values hv106_20 HV106   
label values hv107_01 HV107   
label values hv107_02 HV107   
label values hv107_03 HV107   
label values hv107_04 HV107   
label values hv107_05 HV107   
label values hv107_06 HV107   
label values hv107_07 HV107   
label values hv107_08 HV107   
label values hv107_09 HV107   
label values hv107_10 HV107   
label values hv107_11 HV107   
label values hv107_12 HV107   
label values hv107_13 HV107   
label values hv107_14 HV107   
label values hv107_15 HV107   
label values hv107_16 HV107   
label values hv107_17 HV107   
label values hv107_18 HV107   
label values hv107_19 HV107   
label values hv107_20 HV107   
label values hv108_01 HV108   
label values hv108_02 HV108   
label values hv108_03 HV108   
label values hv108_04 HV108   
label values hv108_05 HV108   
label values hv108_06 HV108   
label values hv108_07 HV108   
label values hv108_08 HV108   
label values hv108_09 HV108   
label values hv108_10 HV108   
label values hv108_11 HV108   
label values hv108_12 HV108   
label values hv108_13 HV108   
label values hv108_14 HV108   
label values hv108_15 HV108   
label values hv108_16 HV108   
label values hv108_17 HV108   
label values hv108_18 HV108   
label values hv108_19 HV108   
label values hv108_20 HV108   
label values hv109_01 HV109   
label values hv109_02 HV109   
label values hv109_03 HV109   
label values hv109_04 HV109   
label values hv109_05 HV109   
label values hv109_06 HV109   
label values hv109_07 HV109   
label values hv109_08 HV109   
label values hv109_09 HV109   
label values hv109_10 HV109   
label values hv109_11 HV109   
label values hv109_12 HV109   
label values hv109_13 HV109   
label values hv109_14 HV109   
label values hv109_15 HV109   
label values hv109_16 HV109   
label values hv109_17 HV109   
label values hv109_18 HV109   
label values hv109_19 HV109   
label values hv109_20 HV109   
label values hv110_01 HV110   
label values hv110_02 HV110   
label values hv110_03 HV110   
label values hv110_04 HV110   
label values hv110_05 HV110   
label values hv110_06 HV110   
label values hv110_07 HV110   
label values hv110_08 HV110   
label values hv110_09 HV110   
label values hv110_10 HV110   
label values hv110_11 HV110   
label values hv110_12 HV110   
label values hv110_13 HV110   
label values hv110_14 HV110   
label values hv110_15 HV110   
label values hv110_16 HV110   
label values hv110_17 HV110   
label values hv110_18 HV110   
label values hv110_19 HV110   
label values hv110_20 HV110   
label values hv111_01 HV111   
label values hv111_02 HV111   
label values hv111_03 HV111   
label values hv111_04 HV111   
label values hv111_05 HV111   
label values hv111_06 HV111   
label values hv111_07 HV111   
label values hv111_08 HV111   
label values hv111_09 HV111   
label values hv111_10 HV111   
label values hv111_11 HV111   
label values hv111_12 HV111   
label values hv111_13 HV111   
label values hv111_14 HV111   
label values hv111_15 HV111   
label values hv111_16 HV111   
label values hv111_17 HV111   
label values hv111_18 HV111   
label values hv111_19 HV111   
label values hv111_20 HV111   
label values hv112_01 HV112   
label values hv112_02 HV112   
label values hv112_03 HV112   
label values hv112_04 HV112   
label values hv112_05 HV112   
label values hv112_06 HV112   
label values hv112_07 HV112   
label values hv112_08 HV112   
label values hv112_09 HV112   
label values hv112_10 HV112   
label values hv112_11 HV112   
label values hv112_12 HV112   
label values hv112_13 HV112   
label values hv112_14 HV112   
label values hv112_15 HV112   
label values hv112_16 HV112   
label values hv112_17 HV112   
label values hv112_18 HV112   
label values hv112_19 HV112   
label values hv112_20 HV112   
label values hv113_01 HV113   
label values hv113_02 HV113   
label values hv113_03 HV113   
label values hv113_04 HV113   
label values hv113_05 HV113   
label values hv113_06 HV113   
label values hv113_07 HV113   
label values hv113_08 HV113   
label values hv113_09 HV113   
label values hv113_10 HV113   
label values hv113_11 HV113   
label values hv113_12 HV113   
label values hv113_13 HV113   
label values hv113_14 HV113   
label values hv113_15 HV113   
label values hv113_16 HV113   
label values hv113_17 HV113   
label values hv113_18 HV113   
label values hv113_19 HV113   
label values hv113_20 HV113   
label values hv114_01 HV114   
label values hv114_02 HV114   
label values hv114_03 HV114   
label values hv114_04 HV114   
label values hv114_05 HV114   
label values hv114_06 HV114   
label values hv114_07 HV114   
label values hv114_08 HV114   
label values hv114_09 HV114   
label values hv114_10 HV114   
label values hv114_11 HV114   
label values hv114_12 HV114   
label values hv114_13 HV114   
label values hv114_14 HV114   
label values hv114_15 HV114   
label values hv114_16 HV114   
label values hv114_17 HV114   
label values hv114_18 HV114   
label values hv114_19 HV114   
label values hv114_20 HV114   
label values hv117_01 HV117   
label values hv117_02 HV117   
label values hv117_03 HV117   
label values hv117_04 HV117   
label values hv117_05 HV117   
label values hv117_06 HV117   
label values hv117_07 HV117   
label values hv117_08 HV117   
label values hv117_09 HV117   
label values hv117_10 HV117   
label values hv117_11 HV117   
label values hv117_12 HV117   
label values hv117_13 HV117   
label values hv117_14 HV117   
label values hv117_15 HV117   
label values hv117_16 HV117   
label values hv117_17 HV117   
label values hv117_18 HV117   
label values hv117_19 HV117   
label values hv117_20 HV117   
label values hv118_01 HV118   
label values hv118_02 HV118   
label values hv118_03 HV118   
label values hv118_04 HV118   
label values hv118_05 HV118   
label values hv118_06 HV118   
label values hv118_07 HV118   
label values hv118_08 HV118   
label values hv118_09 HV118   
label values hv118_10 HV118   
label values hv118_11 HV118   
label values hv118_12 HV118   
label values hv118_13 HV118   
label values hv118_14 HV118   
label values hv118_15 HV118   
label values hv118_16 HV118   
label values hv118_17 HV118   
label values hv118_18 HV118   
label values hv118_19 HV118   
label values hv118_20 HV118   
label values hv120_01 HV120   
label values hv120_02 HV120   
label values hv120_03 HV120   
label values hv120_04 HV120   
label values hv120_05 HV120   
label values hv120_06 HV120   
label values hv120_07 HV120   
label values hv120_08 HV120   
label values hv120_09 HV120   
label values hv120_10 HV120   
label values hv120_11 HV120   
label values hv120_12 HV120   
label values hv120_13 HV120   
label values hv120_14 HV120   
label values hv120_15 HV120   
label values hv120_16 HV120   
label values hv120_17 HV120   
label values hv120_18 HV120   
label values hv120_19 HV120   
label values hv120_20 HV120   
label values hv121_01 HV121   
label values hv121_02 HV121   
label values hv121_03 HV121   
label values hv121_04 HV121   
label values hv121_05 HV121   
label values hv121_06 HV121   
label values hv121_07 HV121   
label values hv121_08 HV121   
label values hv121_09 HV121   
label values hv121_10 HV121   
label values hv121_11 HV121   
label values hv121_12 HV121   
label values hv121_13 HV121   
label values hv121_14 HV121   
label values hv121_15 HV121   
label values hv121_16 HV121   
label values hv121_17 HV121   
label values hv121_18 HV121   
label values hv121_19 HV121   
label values hv121_20 HV121   
label values hv122_01 HV122   
label values hv122_02 HV122   
label values hv122_03 HV122   
label values hv122_04 HV122   
label values hv122_05 HV122   
label values hv122_06 HV122   
label values hv122_07 HV122   
label values hv122_08 HV122   
label values hv122_09 HV122   
label values hv122_10 HV122   
label values hv122_11 HV122   
label values hv122_12 HV122   
label values hv122_13 HV122   
label values hv122_14 HV122   
label values hv122_15 HV122   
label values hv122_16 HV122   
label values hv122_17 HV122   
label values hv122_18 HV122   
label values hv122_19 HV122   
label values hv122_20 HV122   
label values hv123_01 HV123   
label values hv123_02 HV123   
label values hv123_03 HV123   
label values hv123_04 HV123   
label values hv123_05 HV123   
label values hv123_06 HV123   
label values hv123_07 HV123   
label values hv123_08 HV123   
label values hv123_09 HV123   
label values hv123_10 HV123   
label values hv123_11 HV123   
label values hv123_12 HV123   
label values hv123_13 HV123   
label values hv123_14 HV123   
label values hv123_15 HV123   
label values hv123_16 HV123   
label values hv123_17 HV123   
label values hv123_18 HV123   
label values hv123_19 HV123   
label values hv123_20 HV123   
label values hv124_01 HV124   
label values hv124_02 HV124   
label values hv124_03 HV124   
label values hv124_04 HV124   
label values hv124_05 HV124   
label values hv124_06 HV124   
label values hv124_07 HV124   
label values hv124_08 HV124   
label values hv124_09 HV124   
label values hv124_10 HV124   
label values hv124_11 HV124   
label values hv124_12 HV124   
label values hv124_13 HV124   
label values hv124_14 HV124   
label values hv124_15 HV124   
label values hv124_16 HV124   
label values hv124_17 HV124   
label values hv124_18 HV124   
label values hv124_19 HV124   
label values hv124_20 HV124   
label values hv125_01 HV125   
label values hv125_02 HV125   
label values hv125_03 HV125   
label values hv125_04 HV125   
label values hv125_05 HV125   
label values hv125_06 HV125   
label values hv125_07 HV125   
label values hv125_08 HV125   
label values hv125_09 HV125   
label values hv125_10 HV125   
label values hv125_11 HV125   
label values hv125_12 HV125   
label values hv125_13 HV125   
label values hv125_14 HV125   
label values hv125_15 HV125   
label values hv125_16 HV125   
label values hv125_17 HV125   
label values hv125_18 HV125   
label values hv125_19 HV125   
label values hv125_20 HV125   
label values hv126_01 HV126   
label values hv126_02 HV126   
label values hv126_03 HV126   
label values hv126_04 HV126   
label values hv126_05 HV126   
label values hv126_06 HV126   
label values hv126_07 HV126   
label values hv126_08 HV126   
label values hv126_09 HV126   
label values hv126_10 HV126   
label values hv126_11 HV126   
label values hv126_12 HV126   
label values hv126_13 HV126   
label values hv126_14 HV126   
label values hv126_15 HV126   
label values hv126_16 HV126   
label values hv126_17 HV126   
label values hv126_18 HV126   
label values hv126_19 HV126   
label values hv126_20 HV126   
label values hv127_01 HV127   
label values hv127_02 HV127   
label values hv127_03 HV127   
label values hv127_04 HV127   
label values hv127_05 HV127   
label values hv127_06 HV127   
label values hv127_07 HV127   
label values hv127_08 HV127   
label values hv127_09 HV127   
label values hv127_10 HV127   
label values hv127_11 HV127   
label values hv127_12 HV127   
label values hv127_13 HV127   
label values hv127_14 HV127   
label values hv127_15 HV127   
label values hv127_16 HV127   
label values hv127_17 HV127   
label values hv127_18 HV127   
label values hv127_19 HV127   
label values hv127_20 HV127   
label values hv128_01 HV128   
label values hv128_02 HV128   
label values hv128_03 HV128   
label values hv128_04 HV128   
label values hv128_05 HV128   
label values hv128_06 HV128   
label values hv128_07 HV128   
label values hv128_08 HV128   
label values hv128_09 HV128   
label values hv128_10 HV128   
label values hv128_11 HV128   
label values hv128_12 HV128   
label values hv128_13 HV128   
label values hv128_14 HV128   
label values hv128_15 HV128   
label values hv128_16 HV128   
label values hv128_17 HV128   
label values hv128_18 HV128   
label values hv128_19 HV128   
label values hv128_20 HV128   
label values hv129_01 HV129   
label values hv129_02 HV129   
label values hv129_03 HV129   
label values hv129_04 HV129   
label values hv129_05 HV129   
label values hv129_06 HV129   
label values hv129_07 HV129   
label values hv129_08 HV129   
label values hv129_09 HV129   
label values hv129_10 HV129   
label values hv129_11 HV129   
label values hv129_12 HV129   
label values hv129_13 HV129   
label values hv129_14 HV129   
label values hv129_15 HV129   
label values hv129_16 HV129   
label values hv129_17 HV129   
label values hv129_18 HV129   
label values hv129_19 HV129   
label values hv129_20 HV129   
label values sh03_01  SH03    
label values sh03_02  SH03    
label values sh03_03  SH03    
label values sh03_04  SH03    
label values sh03_05  SH03    
label values sh03_06  SH03    
label values sh03_07  SH03    
label values sh03_08  SH03    
label values sh03_09  SH03    
label values sh03_10  SH03    
label values sh03_11  SH03    
label values sh03_12  SH03    
label values sh03_13  SH03    
label values sh03_14  SH03    
label values sh03_15  SH03    
label values sh03_16  SH03    
label values sh03_17  SH03    
label values sh03_18  SH03    
label values sh03_19  SH03    
label values sh03_20  SH03    
label values sh15a_01 SH15A   
label values sh15a_02 SH15A   
label values sh15a_03 SH15A   
label values sh15a_04 SH15A   
label values sh15a_05 SH15A   
label values sh15a_06 SH15A   
label values sh15a_07 SH15A   
label values sh15a_08 SH15A   
label values sh15a_09 SH15A   
label values sh15a_10 SH15A   
label values sh15a_11 SH15A   
label values sh15a_12 SH15A   
label values sh15a_13 SH15A   
label values sh15a_14 SH15A   
label values sh15a_15 SH15A   
label values sh15a_16 SH15A   
label values sh15a_17 SH15A   
label values sh15a_18 SH15A   
label values sh15a_19 SH15A   
label values sh15a_20 SH15A   
label values sh16_01  SH16    
label values sh16_02  SH16    
label values sh16_03  SH16    
label values sh16_04  SH16    
label values sh16_05  SH16    
label values sh16_06  SH16    
label values sh16_07  SH16    
label values sh16_08  SH16    
label values sh16_09  SH16    
label values sh16_10  SH16    
label values sh16_11  SH16    
label values sh16_12  SH16    
label values sh16_13  SH16    
label values sh16_14  SH16    
label values sh16_15  SH16    
label values sh16_16  SH16    
label values sh16_17  SH16    
label values sh16_18  SH16    
label values sh16_19  SH16    
label values sh16_20  SH16    
label values sh17_01  SH17    
label values sh17_02  SH17    
label values sh17_03  SH17    
label values sh17_04  SH17    
label values sh17_05  SH17    
label values sh17_06  SH17    
label values sh17_07  SH17    
label values sh17_08  SH17    
label values sh17_09  SH17    
label values sh17_10  SH17    
label values sh17_11  SH17    
label values sh17_12  SH17    
label values sh17_13  SH17    
label values sh17_14  SH17    
label values sh17_15  SH17    
label values sh17_16  SH17    
label values sh17_17  SH17    
label values sh17_18  SH17    
label values sh17_19  SH17    
label values sh17_20  SH17    
label values sh18a_01 SH18A   
label values sh18a_02 SH18A   
label values sh18a_03 SH18A   
label values sh18a_04 SH18A   
label values sh18a_05 SH18A   
label values sh18a_06 SH18A   
label values sh18a_07 SH18A   
label values sh18a_08 SH18A   
label values sh18a_09 SH18A   
label values sh18a_10 SH18A   
label values sh18a_11 SH18A   
label values sh18a_12 SH18A   
label values sh18a_13 SH18A   
label values sh18a_14 SH18A   
label values sh18a_15 SH18A   
label values sh18a_16 SH18A   
label values sh18a_17 SH18A   
label values sh18a_18 SH18A   
label values sh18a_19 SH18A   
label values sh18a_20 SH18A   
label values sh18b_01 SH18B   
label values sh18b_02 SH18B   
label values sh18b_03 SH18B   
label values sh18b_04 SH18B   
label values sh18b_05 SH18B   
label values sh18b_06 SH18B   
label values sh18b_07 SH18B   
label values sh18b_08 SH18B   
label values sh18b_09 SH18B   
label values sh18b_10 SH18B   
label values sh18b_11 SH18B   
label values sh18b_12 SH18B   
label values sh18b_13 SH18B   
label values sh18b_14 SH18B   
label values sh18b_15 SH18B   
label values sh18b_16 SH18B   
label values sh18b_17 SH18B   
label values sh18b_18 SH18B   
label values sh18b_19 SH18B   
label values sh18b_20 SH18B   
label values sh19_01  SH19    
label values sh19_02  SH19    
label values sh19_03  SH19    
label values sh19_04  SH19    
label values sh19_05  SH19    
label values sh19_06  SH19    
label values sh19_07  SH19    
label values sh19_08  SH19    
label values sh19_09  SH19    
label values sh19_10  SH19    
label values sh19_11  SH19    
label values sh19_12  SH19    
label values sh19_13  SH19    
label values sh19_14  SH19    
label values sh19_15  SH19    
label values sh19_16  SH19    
label values sh19_17  SH19    
label values sh19_18  SH19    
label values sh19_19  SH19    
label values sh19_20  SH19    
label values sh20a_01 SH20A   
label values sh20a_02 SH20A   
label values sh20a_03 SH20A   
label values sh20a_04 SH20A   
label values sh20a_05 SH20A   
label values sh20a_06 SH20A   
label values sh20a_07 SH20A   
label values sh20a_08 SH20A   
label values sh20a_09 SH20A   
label values sh20a_10 SH20A   
label values sh20a_11 SH20A   
label values sh20a_12 SH20A   
label values sh20a_13 SH20A   
label values sh20a_14 SH20A   
label values sh20a_15 SH20A   
label values sh20a_16 SH20A   
label values sh20a_17 SH20A   
label values sh20a_18 SH20A   
label values sh20a_19 SH20A   
label values sh20a_20 SH20A   
label values sh20b_01 SH20B   
label values sh20b_02 SH20B   
label values sh20b_03 SH20B   
label values sh20b_04 SH20B   
label values sh20b_05 SH20B   
label values sh20b_06 SH20B   
label values sh20b_07 SH20B   
label values sh20b_08 SH20B   
label values sh20b_09 SH20B   
label values sh20b_10 SH20B   
label values sh20b_11 SH20B   
label values sh20b_12 SH20B   
label values sh20b_13 SH20B   
label values sh20b_14 SH20B   
label values sh20b_15 SH20B   
label values sh20b_16 SH20B   
label values sh20b_17 SH20B   
label values sh20b_18 SH20B   
label values sh20b_19 SH20B   
label values sh20b_20 SH20B   
label values ha4_01   HA4     
label values ha4_02   HA4     
label values ha4_03   HA4     
label values ha4_04   HA4     
label values ha4_05   HA4     
label values ha4_06   HA4     
label values ha4_07   HA4     
label values ha4_08   HA4     
label values ha4_09   HA4     
label values ha4_10   HA4     
label values ha4_11   HA4     
label values ha4_12   HA4     
label values ha4_13   HA4     
label values ha4_14   HA4     
label values ha4_15   HA4     
label values ha5_01   HA5     
label values ha5_02   HA5     
label values ha5_03   HA5     
label values ha5_04   HA5     
label values ha5_05   HA5     
label values ha5_06   HA5     
label values ha5_07   HA5     
label values ha5_08   HA5     
label values ha5_09   HA5     
label values ha5_10   HA5     
label values ha5_11   HA5     
label values ha5_12   HA5     
label values ha5_13   HA5     
label values ha5_14   HA5     
label values ha5_15   HA5     
label values ha6_01   HA6     
label values ha6_02   HA6     
label values ha6_03   HA6     
label values ha6_04   HA6     
label values ha6_05   HA6     
label values ha6_06   HA6     
label values ha6_07   HA6     
label values ha6_08   HA6     
label values ha6_09   HA6     
label values ha6_10   HA6     
label values ha6_11   HA6     
label values ha6_12   HA6     
label values ha6_13   HA6     
label values ha6_14   HA6     
label values ha6_15   HA6     
label values ha11_01  HA11    
label values ha11_02  HA11    
label values ha11_03  HA11    
label values ha11_04  HA11    
label values ha11_05  HA11    
label values ha11_06  HA11    
label values ha11_07  HA11    
label values ha11_08  HA11    
label values ha11_09  HA11    
label values ha11_10  HA11    
label values ha11_11  HA11    
label values ha11_12  HA11    
label values ha11_13  HA11    
label values ha11_14  HA11    
label values ha11_15  HA11    
label values ha12_01  HA12    
label values ha12_02  HA12    
label values ha12_03  HA12    
label values ha12_04  HA12    
label values ha12_05  HA12    
label values ha12_06  HA12    
label values ha12_07  HA12    
label values ha12_08  HA12    
label values ha12_09  HA12    
label values ha12_10  HA12    
label values ha12_11  HA12    
label values ha12_12  HA12    
label values ha12_13  HA12    
label values ha12_14  HA12    
label values ha12_15  HA12    
label values ha12a_01 HA12A   
label values ha12a_02 HA12A   
label values ha12a_03 HA12A   
label values ha12a_04 HA12A   
label values ha12a_05 HA12A   
label values ha12a_06 HA12A   
label values ha12a_07 HA12A   
label values ha12a_08 HA12A   
label values ha12a_09 HA12A   
label values ha12a_10 HA12A   
label values ha12a_11 HA12A   
label values ha12a_12 HA12A   
label values ha12a_13 HA12A   
label values ha12a_14 HA12A   
label values ha12a_15 HA12A   
label values ha12b_01 HA12B   
label values ha12b_02 HA12B   
label values ha12b_03 HA12B   
label values ha12b_04 HA12B   
label values ha12b_05 HA12B   
label values ha12b_06 HA12B   
label values ha12b_07 HA12B   
label values ha12b_08 HA12B   
label values ha12b_09 HA12B   
label values ha12b_10 HA12B   
label values ha12b_11 HA12B   
label values ha12b_12 HA12B   
label values ha12b_13 HA12B   
label values ha12b_14 HA12B   
label values ha12b_15 HA12B   
label values ha13_01  HA13    
label values ha13_02  HA13    
label values ha13_03  HA13    
label values ha13_04  HA13    
label values ha13_05  HA13    
label values ha13_06  HA13    
label values ha13_07  HA13    
label values ha13_08  HA13    
label values ha13_09  HA13    
label values ha13_10  HA13    
label values ha13_11  HA13    
label values ha13_12  HA13    
label values ha13_13  HA13    
label values ha13_14  HA13    
label values ha13_15  HA13    
label values ha33_01  HA33    
label values ha33_02  HA33    
label values ha33_03  HA33    
label values ha33_04  HA33    
label values ha33_05  HA33    
label values ha33_06  HA33    
label values ha33_07  HA33    
label values ha33_08  HA33    
label values ha33_09  HA33    
label values ha33_10  HA33    
label values ha33_11  HA33    
label values ha33_12  HA33    
label values ha33_13  HA33    
label values ha33_14  HA33    
label values ha33_15  HA33    
label values ha40_01  HA40    
label values ha40_02  HA40    
label values ha40_03  HA40    
label values ha40_04  HA40    
label values ha40_05  HA40    
label values ha40_06  HA40    
label values ha40_07  HA40    
label values ha40_08  HA40    
label values ha40_09  HA40    
label values ha40_10  HA40    
label values ha40_11  HA40    
label values ha40_12  HA40    
label values ha40_13  HA40    
label values ha40_14  HA40    
label values ha40_15  HA40    
label values ha41_01  HA41    
label values ha41_02  HA41    
label values ha41_03  HA41    
label values ha41_04  HA41    
label values ha41_05  HA41    
label values ha41_06  HA41    
label values ha41_07  HA41    
label values ha41_08  HA41    
label values ha41_09  HA41    
label values ha41_10  HA41    
label values ha41_11  HA41    
label values ha41_12  HA41    
label values ha41_13  HA41    
label values ha41_14  HA41    
label values ha41_15  HA41    
label values hc4_01   HC4     
label values hc4_02   HC4     
label values hc4_03   HC4     
label values hc4_04   HC4     
label values hc4_05   HC4     
label values hc4_06   HC4     
label values hc4_07   HC4     
label values hc4_08   HC4     
label values hc4_09   HC4     
label values hc4_10   HC4     
label values hc4_11   HC4     
label values hc4_12   HC4     
label values hc4_13   HC4     
label values hc4_14   HC4     
label values hc4_15   HC4     
label values hc5_01   HC5     
label values hc5_02   HC5     
label values hc5_03   HC5     
label values hc5_04   HC5     
label values hc5_05   HC5     
label values hc5_06   HC5     
label values hc5_07   HC5     
label values hc5_08   HC5     
label values hc5_09   HC5     
label values hc5_10   HC5     
label values hc5_11   HC5     
label values hc5_12   HC5     
label values hc5_13   HC5     
label values hc5_14   HC5     
label values hc5_15   HC5     
label values hc6_01   HC6     
label values hc6_02   HC6     
label values hc6_03   HC6     
label values hc6_04   HC6     
label values hc6_05   HC6     
label values hc6_06   HC6     
label values hc6_07   HC6     
label values hc6_08   HC6     
label values hc6_09   HC6     
label values hc6_10   HC6     
label values hc6_11   HC6     
label values hc6_12   HC6     
label values hc6_13   HC6     
label values hc6_14   HC6     
label values hc6_15   HC6     
label values hc7_01   HC7     
label values hc7_02   HC7     
label values hc7_03   HC7     
label values hc7_04   HC7     
label values hc7_05   HC7     
label values hc7_06   HC7     
label values hc7_07   HC7     
label values hc7_08   HC7     
label values hc7_09   HC7     
label values hc7_10   HC7     
label values hc7_11   HC7     
label values hc7_12   HC7     
label values hc7_13   HC7     
label values hc7_14   HC7     
label values hc7_15   HC7     
label values hc8_01   HC8     
label values hc8_02   HC8     
label values hc8_03   HC8     
label values hc8_04   HC8     
label values hc8_05   HC8     
label values hc8_06   HC8     
label values hc8_07   HC8     
label values hc8_08   HC8     
label values hc8_09   HC8     
label values hc8_10   HC8     
label values hc8_11   HC8     
label values hc8_12   HC8     
label values hc8_13   HC8     
label values hc8_14   HC8     
label values hc8_15   HC8     
label values hc9_01   HC9     
label values hc9_02   HC9     
label values hc9_03   HC9     
label values hc9_04   HC9     
label values hc9_05   HC9     
label values hc9_06   HC9     
label values hc9_07   HC9     
label values hc9_08   HC9     
label values hc9_09   HC9     
label values hc9_10   HC9     
label values hc9_11   HC9     
label values hc9_12   HC9     
label values hc9_13   HC9     
label values hc9_14   HC9     
label values hc9_15   HC9     
label values hc10_01  HC10    
label values hc10_02  HC10    
label values hc10_03  HC10    
label values hc10_04  HC10    
label values hc10_05  HC10    
label values hc10_06  HC10    
label values hc10_07  HC10    
label values hc10_08  HC10    
label values hc10_09  HC10    
label values hc10_10  HC10    
label values hc10_11  HC10    
label values hc10_12  HC10    
label values hc10_13  HC10    
label values hc10_14  HC10    
label values hc10_15  HC10    
label values hc11_01  HC11    
label values hc11_02  HC11    
label values hc11_03  HC11    
label values hc11_04  HC11    
label values hc11_05  HC11    
label values hc11_06  HC11    
label values hc11_07  HC11    
label values hc11_08  HC11    
label values hc11_09  HC11    
label values hc11_10  HC11    
label values hc11_11  HC11    
label values hc11_12  HC11    
label values hc11_13  HC11    
label values hc11_14  HC11    
label values hc11_15  HC11    
label values hc12_01  HC12    
label values hc12_02  HC12    
label values hc12_03  HC12    
label values hc12_04  HC12    
label values hc12_05  HC12    
label values hc12_06  HC12    
label values hc12_07  HC12    
label values hc12_08  HC12    
label values hc12_09  HC12    
label values hc12_10  HC12    
label values hc12_11  HC12    
label values hc12_12  HC12    
label values hc12_13  HC12    
label values hc12_14  HC12    
label values hc12_15  HC12    
label values hc13_01  HC13    
label values hc13_02  HC13    
label values hc13_03  HC13    
label values hc13_04  HC13    
label values hc13_05  HC13    
label values hc13_06  HC13    
label values hc13_07  HC13    
label values hc13_08  HC13    
label values hc13_09  HC13    
label values hc13_10  HC13    
label values hc13_11  HC13    
label values hc13_12  HC13    
label values hc13_13  HC13    
label values hc13_14  HC13    
label values hc13_15  HC13    
label values hc15_01  HC15    
label values hc15_02  HC15    
label values hc15_03  HC15    
label values hc15_04  HC15    
label values hc15_05  HC15    
label values hc15_06  HC15    
label values hc15_07  HC15    
label values hc15_08  HC15    
label values hc15_09  HC15    
label values hc15_10  HC15    
label values hc15_11  HC15    
label values hc15_12  HC15    
label values hc15_13  HC15    
label values hc15_14  HC15    
label values hc15_15  HC15    
label values hc27_01  HC27    
label values hc27_02  HC27    
label values hc27_03  HC27    
label values hc27_04  HC27    
label values hc27_05  HC27    
label values hc27_06  HC27    
label values hc27_07  HC27    
label values hc27_08  HC27    
label values hc27_09  HC27    
label values hc27_10  HC27    
label values hc27_11  HC27    
label values hc27_12  HC27    
label values hc27_13  HC27    
label values hc27_14  HC27    
label values hc27_15  HC27    
label values hc30_01  HC30    
label values hc30_02  HC30    
label values hc30_03  HC30    
label values hc30_04  HC30    
label values hc30_05  HC30    
label values hc30_06  HC30    
label values hc30_07  HC30    
label values hc30_08  HC30    
label values hc30_09  HC30    
label values hc30_10  HC30    
label values hc30_11  HC30    
label values hc30_12  HC30    
label values hc30_13  HC30    
label values hc30_14  HC30    
label values hc30_15  HC30    
label values hc31_01  HC31    
label values hc31_02  HC31    
label values hc31_03  HC31    
label values hc31_04  HC31    
label values hc31_05  HC31    
label values hc31_06  HC31    
label values hc31_07  HC31    
label values hc31_08  HC31    
label values hc31_09  HC31    
label values hc31_10  HC31    
label values hc31_11  HC31    
label values hc31_12  HC31    
label values hc31_13  HC31    
label values hc31_14  HC31    
label values hc31_15  HC31    
label values hc33_01  HC33    
label values hc33_02  HC33    
label values hc33_03  HC33    
label values hc33_04  HC33    
label values hc33_05  HC33    
label values hc33_06  HC33    
label values hc33_07  HC33    
label values hc33_08  HC33    
label values hc33_09  HC33    
label values hc33_10  HC33    
label values hc33_11  HC33    
label values hc33_12  HC33    
label values hc33_13  HC33    
label values hc33_14  HC33    
label values hc33_15  HC33    
label values hc60_01  HC60    
label values hc60_02  HC60    
label values hc60_03  HC60    
label values hc60_04  HC60    
label values hc60_05  HC60    
label values hc60_06  HC60    
label values hc60_07  HC60    
label values hc60_08  HC60    
label values hc60_09  HC60    
label values hc60_10  HC60    
label values hc60_11  HC60    
label values hc60_12  HC60    
label values hc60_13  HC60    
label values hc60_14  HC60    
label values hc60_15  HC60    
label values hc61_01  HC61    
label values hc61_02  HC61    
label values hc61_03  HC61    
label values hc61_04  HC61    
label values hc61_05  HC61    
label values hc61_06  HC61    
label values hc61_07  HC61    
label values hc61_08  HC61    
label values hc61_09  HC61    
label values hc61_10  HC61    
label values hc61_11  HC61    
label values hc61_12  HC61    
label values hc61_13  HC61    
label values hc61_14  HC61    
label values hc61_15  HC61    
label values hc65_01  HC65    
label values hc65_02  HC65    
label values hc65_03  HC65    
label values hc65_04  HC65    
label values hc65_05  HC65    
label values hc65_06  HC65    
label values hc65_07  HC65    
label values hc65_08  HC65    
label values hc65_09  HC65    
label values hc65_10  HC65    
label values hc65_11  HC65    
label values hc65_12  HC65    
label values hc65_13  HC65    
label values hc65_14  HC65    
label values hc65_15  HC65    
label values hc66_01  HC66    
label values hc66_02  HC66    
label values hc66_03  HC66    
label values hc66_04  HC66    
label values hc66_05  HC66    
label values hc66_06  HC66    
label values hc66_07  HC66    
label values hc66_08  HC66    
label values hc66_09  HC66    
label values hc66_10  HC66    
label values hc66_11  HC66    
label values hc66_12  HC66    
label values hc66_13  HC66    
label values hc66_14  HC66    
label values hc66_15  HC66    
